%LET PROJECT = SALMON;
%LET YEAR = 1996 - 2000;
%LET SPECIES = SALMON;
LIBNAME SASDATA BASE "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
RUN;


DATA EXCEL; SET SASDATA.harv99;
RUN;


PROC EXPORT DATA= EXCEL
            OUTFILE= "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR\DATA 1999.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="DATA"; 
RUN;



