%LET PROJECT = SALMON;
%LET DATA = CISLHV06C;
%LET YEAR = 2006;
%LET SP = SALMON;
%LET SPECIES_COMMA = RED,KING,COHO,PINK,CHUM,FLOUNDER; 
%LET SPECIES_LIST = RED KING COHO PINK CHUM FLOUNDER; 
%LET PROGRAM = HARVEST;
%LET GILLNET_START = '15JUN06'D; 
%LET GILLNET_STOP = '24JUN06'D; 


OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
LIBNAME SASDATA BASE "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
RUN;


TITLE1 "&PROJECT - &YEAR";


**************************************************************************;
*                              HARVEST DATA                              *;
**************************************************************************;

DATA HARVEST; SET SASDATA.&DATA (DROP =  YEAR KEYDATE HVRECID MAILING KEYID EDITED);
     SPECIES = 'SALMON';  
   * IF HARVDATE EQ '01JAN01'D THEN HARVDATE = .;
     IF NOCATCH = 1 THEN CATCH = 'N'; IF NOCATCH NE 1 THEN CATCH = 'Y';
     IF NOHRVRPT = 1 THEN HRVRPT = 'N'; IF NOHRVRPT NE 1 THEN HRVRPT = 'Y';
     IF FISHERY = '' THEN FISHERY = 'UNKNOWN';
     RENAME PERMITNO = PERMIT;
     DROP NOCATCH NOHRVRPT COMMENTS;
RUN;

DATA HARVEST; SET HARVEST;
     MONTH = MONTH(HARVDATE);
     DAY = DAY(HARVDATE);
     IF FISHERY = 'KENAI' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KENAI' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 6 AND DAY LT 15 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 8 AND DAY GT 7 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'UNKNOWN' AND MONTH = 6 AND DAY GE 15 THEN FISHERY = 'KASILOF';
     IF FISHERY = 'UNKNOWN' AND MONTH = 7 AND DAY LE 9 THEN FISHERY = 'KASILOF';
     IF FISHERY = 'UNKNOWN' AND MONTH = 8 AND DAY GE 1 AND DAY LE 7 THEN FISHERY = 'KASILOF';

     IF FISHERY = 'UNKNOWN' AND MONTH = 7 AND DAY GE 10 THEN FISHERY = 'UNK FIXABLE';
RUN;


PROC SORT; BY PERMIT HARVDATE FISHERY;

DATA UNKNOWN; SET HARVEST;
     IF FISHERY = 'UNK FIXABLE';

PROC SORT; BY PERMIT;
PROC SORT DATA = SASDATA.ISSUED; BY PERMIT;
PROC SORT DATA = SASDATA.PERSONAL; BY PERMIT;

DATA FIXABLE_UNKNOWNS; MERGE UNKNOWN (IN=INH) SASDATA.ISSUED (IN=INP) SASDATA.PERSONAL (IN=INJ); BY PERMIT;  
     IF INH THEN HARVFILE=1;
     IF INP THEN PERMFILE=1;
     IF INJ THEN PERSONALFILE=1;
	IF HARVFILE NE 1 THEN DELETE;
RUN;

PROC CONTENTS;
RUN;

DATA FIXABLE_UNKNOWNS; SET FIXABLE_UNKNOWNS;
     KEEP FISHERY PERMIT	FIRST_NAME LAST_NAME PHONE HARVDATE RED KING PINK CHUM COHO FLOUNDER;
PROC PRINT;
RUN;


PROC EXPORT DATA= WORK.FIXABLE_UNKNOWNS OUTFILE= "H:\common\PAT\Permits\Salmon\2006\UNKNOWN HARVEST RECORDS.xls" DBMS=EXCEL REPLACE;
     SHEET="UNKNOWN"; 
RUN;


