%LET PROJECT = SALMON;
%LET DATA = cislpm17c;
%LET YEAR = 2017;
%LET PROGRAM = PERMIT;
%LET RESPONSE_RATE = 90;



OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR";
RUN;

TITLE1 "&PROJECT - &YEAR - Nonresponse Problem";

DATA ISSUED; SET SASDATA.ISSUED;
DATA HARVEST; SET SASDATA.SALMON_HARVEST; 

LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\NONRESPONSE PROBLEM";


DATA ISSUED; SET ISSUED;
     IF RESPONDED = 'Y';
     MERGEVAR = 1;
     DROP VENDORCOPY RESPONDED;

PROC MEANS NOPRINT DATA = ISSUED; 
     VAR MERGEVAR;
	 OUTPUT OUT = TOTAL_ISSUED N = NHAT;


DATA TOTAL_ISSUED; SET TOTAL_ISSUED (KEEP = NHAT);
     VAR_NHAT = 0;
PROC PRINT;
RUN;

DATA SASDATA.TOTAL_ISSUED; SET TOTAL_ISSUED;
DATA TOTAL_ISSUED; SET TOTAL_ISSUED;
     MERGEVAR = 1;
RUN;

DATA ISSUED; MERGE ISSUED TOTAL_ISSUED; BY MERGEVAR;
     RANDOM = RANUNI(87087);
	 
PROC SORT DATA = ISSUED; BY RANDOM;
DATA ISSUED; SET ISSUED;
     RANK = _N_;
	 IF RANK LE ((&RESPONSE_RATE/100)*TOTAL_ISSUED) THEN RESPONDED = 'Y';
	 IF RANK GT ((&RESPONSE_RATE/100)*TOTAL_ISSUED) THEN RESPONDED = 'N';

PROC PRINT DATA = ISSUED (OBS = 25);
PROC FREQ DATA = ISSUED;
     TABLES RESPONDED;

DATA ISSUED_&RESPONSE_RATE; SET ISSUED;
     DROP RANDOM RANK MERGEVAR;
RUN;
     
