%LET PROJECT = SALMON;
%LET PROGRAM = EXTRA ESTIMATES;
%LET YEAR = 2015;
%LET SPECIES = SALMON;
RUN;

TITLE1 "&PROJECT - &YEAR";

OPTIONS PAGENO=1 NODATE SYMBOLGEN LINESIZE=119 PAGESIZE=67 ;
LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR";
RUN;

DATA PERMITS; SET SASDATA.ISSUED;
     IF STATUS = 'HARVEST REPORTED';
     PERMITDATA = 1;
	 KEEP PERMIT PERMITDATA;
PROC SORT; BY PERMIT;

DATA PERSONAL; SET SASDATA.PERSONAL;
     C = CITY;
     KEEP PERMIT C;
DATA PERSONAL; SET PERSONAL;
     RENAME C = CITY;
PROC SORT; BY PERMIT;

DATA PERMITS; MERGE PERMITS PERSONAL; BY PERMIT;
     IF PERMITDATA = 1;
RUN;


LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT";

DATA CITIES; SET SASDATA.CITIES;
PROC SORT DATA = CITIES; BY CITY;
PROC SORT DATA = PERMITS; BY CITY;

DATA PERMITS_CITY; MERGE PERMITS CITIES; BY CITY;
     IF PERMITDATA = 1 AND REGION NE .;
     IF NEW_NAME NE '' THEN DO;
	                        CITY = NEW_NAME;
						    END;
     DROP NEW_NAME;
RUN;



LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR";

DATA HARVEST; SET SASDATA.SALMON_HARVEST; 
     IF FISHERY = 'KENAI';
	 SALMON = RED + KING + COHO + PINK + CHUM;
	 HARVESTDATA = 1;
	 DROP FLOUNDER FISHERY SPECIES CATCH HRVRPT MONTH DAY;
PROC SORT DATA = HARVEST; BY PERMIT HARVDATE;
PROC SORT DATA = PERMITS_CITY; BY PERMIT;


DATA PERMITS_HARVEST; MERGE PERMITS_CITY HARVEST; BY PERMIT;
     IF PERMITDATA = 1 AND HARVESTDATA = 1;
RUN;


DATA PERMITS_HARVEST_UNIQUE; SET PERMITS_HARVEST; BY PERMIT;
     IF FIRST.PERMIT;
RUN;

