OPTIONS PAGENO=1;
%LET PROJECT = SALMON;
%LET YEAR = 2003;


LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR" SHORTFILEEXT;
RUN;
DATA ONE; SET SASDATA.cislpm03c;
DATA TWO; SET SASDATA.cislhv03c;
RUN;




LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR";
RUN;

DATA SASDATA.CISLPM03C; SET ONE;
DATA SASDATA.CISLHV03C; SET TWO;


RUN;
