%LET PROJECT = SALMON;
%LET YEAR = 2006;
%LET PROGRAM = UNKNOWN CORRECTION;

OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
LIBNAME SASDATA BASE "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
RUN;

TITLE1 "&PROJECT - &YEAR";
TITLE2 'TRYING TO GET THE CORRECTION FACTOR FOR ALL THE FISHERY = UNKNOWN RECORDS';



PROC IMPORT OUT= WORK.PHONE DATAFILE= "H:\common\PAT\Permits\Salmon\2006\UNKNOWN HARVEST RECORDS_ Survey Results.xls" DBMS=EXCEL REPLACE;
     SHEET="PHONE"; GETNAMES=YES; MIXED=NO; SCANTEXT=YES; USEDATE=YES; SCANTIME=YES;
RUN;
DATA PHONE; SET PHONE;
	PHONE = 'Y';

PROC SORT; BY PERMIT MONTH DAY FISHERY;

DATA HARVEST; SET SASDATA.SALMON_HARVEST;
      MONTH = MONTH(HARVDATE);
      DAY = DAY(HARVDATE);
PROC SORT DATA = HARVEST; BY PERMIT MONTH DAY FISHERY;

DATA HARVEST2; MERGE HARVEST PHONE; BY PERMIT MONTH DAY;
     IF MONTH = 7 AND DAY GE 10 AND FISHERY NE 'UNKNOWN' AND FISHERY NE 'UNK FIXABLE' AND FISHERY NE 'FISH CREEK';
	IF PHONE NE 'Y' THEN PHONE = 'N';

PROC FREQ DATA = HARVEST2; 
     TABLES FISHERY*PHONE / CHISQ;
	TITLE3 'DAYS FISHED';
RUN;

PROC FREQ DATA = HARVEST2;
     WHERE PHONE = 'N'; 
     TABLES FISHERY / NOPRINT OUT = CF_DAYS;
RUN;

DATA CF_DAYS; SET CF_DAYS;
	 IF FISHERY = 'KENAI'   THEN DO;  P_KENAI_DAYS = PERCENT / 100;  END;
	 IF FISHERY = 'KASILOF' THEN DO;  P_KASILOF_DAYS = PERCENT / 100;  END;

PROC MEANS SUM NOPRINT DATA = CF_DAYS;
      VAR P_KENAI_DAYS P_KASILOF_DAYS COUNT;
	 OUTPUT OUT = CF_DAYS SUM = P_KENAI_DAYS P_KASILOF_DAYS N;

DATA CF_DAYS; SET CF_DAYS (DROP = _TYPE_ _FREQ_);
      V_P_DAYS = (P_KENAI_DAYS * (1 - P_KENAI_DAYS)) / (N - 1); 
	 MERGEVAR = 1;
	 DROP N;
PROC PRINT;
RUN; 




PROC SORT DATA = HARVEST2; BY FISHERY PHONE;
PROC UNIVARIATE NORMAL PLOT DATA = HARVEST2; BY FISHERY PHONE;
     VAR RED;
RUN;
PROC FREQ DATA = HARVEST2;  
     TABLES FISHERY*PHONE;
	WEIGHT RED;
	TITLE3 'REDS';
RUN;


PROC SORT DATA = HARVEST2; BY FISHERY PHONE;
PROC UNIVARIATE NORMAL PLOT DATA = HARVEST2; BY FISHERY PHONE;
     WHERE (FISHERY = 'KENAI' AND RED LE 36) OR (FISHERY = 'KASILOF' AND RED LE 30);
     VAR RED;
RUN;
PROC FREQ DATA = HARVEST2;  
     WHERE (FISHERY = 'KENAI' AND RED LE 36) OR (FISHERY = 'KASILOF' AND RED LE 30);
     TABLES FISHERY*PHONE;
	WEIGHT RED;
RUN;
PROC FREQ DATA = HARVEST2;  
     WHERE PHONE = 'N' AND ((FISHERY = 'KENAI' AND RED LE 36) OR (FISHERY = 'KASILOF' AND RED LE 30));
     TABLES FISHERY / NOPRINT OUT = CF_REDS;
	WEIGHT RED;
RUN;

DATA CF_REDS; SET CF_REDS;
      IF FISHERY = 'KENAI'   THEN DO;  P_KENAI_REDS = PERCENT / 100;  END;
      IF FISHERY = 'KASILOF' THEN DO;  P_KASILOF_REDS = PERCENT / 100;  END;

PROC MEANS SUM NOPRINT DATA = CF_REDS;
      VAR P_KENAI_REDS P_KASILOF_REDS COUNT;
      OUTPUT OUT = CF_REDS SUM = P_KENAI_REDS P_KASILOF_REDS N;

DATA CF_REDS; SET CF_REDS (DROP = _TYPE_ _FREQ_);
      V_P_REDS = (P_KENAI_REDS * (1 - P_KENAI_REDS)) / (N - 1); 
      MERGEVAR = 1;
      DROP N;
PROC PRINT;
RUN; 




PROC FREQ DATA = HARVEST2; 
     TABLES FISHERY*PHONE;
	WEIGHT KING;
	TITLE3 'KINGS';
RUN;
PROC FREQ DATA = HARVEST2;
     WHERE PHONE = 'N'; 
     TABLES FISHERY / NOPRINT OUT = CF_KINGS;
	WEIGHT KING;
RUN;


DATA CF_KINGS; SET CF_KINGS;
      IF FISHERY = 'KENAI'   THEN DO;  P_KENAI_KINGS = PERCENT / 100;  END;
      IF FISHERY = 'KASILOF' THEN DO;  P_KASILOF_KINGS = PERCENT / 100;  END;

PROC MEANS SUM NOPRINT DATA = CF_KINGS;
      VAR P_KENAI_KINGS P_KASILOF_KINGS COUNT;
      OUTPUT OUT = CF_KINGS SUM = P_KENAI_KINGS P_KASILOF_KINGS N;

DATA CF_KINGS; SET CF_KINGS (DROP = _TYPE_ _FREQ_);
      V_P_KINGS = (P_KENAI_KINGS * (1 - P_KENAI_KINGS)) / (N - 1); 
      MERGEVAR = 1;
      DROP N;
PROC PRINT;
RUN; 




PROC FREQ DATA = HARVEST2; 
     TABLES FISHERY*PHONE;
     WEIGHT PINK;
	TITLE3 'PINKS';
RUN;
PROC FREQ DATA = HARVEST2;
     WHERE PHONE = 'N'; 
     TABLES FISHERY / NOPRINT OUT = CF_PINKS;
     WEIGHT PINK;
RUN;

DATA CF_PINKS; SET CF_PINKS;
      IF FISHERY = 'KENAI'   THEN DO;  P_KENAI_PINKS = PERCENT / 100;  END;
      IF FISHERY = 'KASILOF' THEN DO;  P_KASILOF_PINKS = PERCENT / 100;  END;

PROC MEANS SUM NOPRINT DATA = CF_PINKS;
      VAR P_KENAI_PINKS P_KASILOF_PINKS COUNT;
      OUTPUT OUT = CF_PINKS SUM = P_KENAI_PINKS P_KASILOF_PINKS N;

DATA CF_PINKS; SET CF_PINKS (DROP = _TYPE_ _FREQ_);
      V_P_PINKS = (P_KENAI_PINKS * (1 - P_KENAI_PINKS)) / (N - 1); 
      MERGEVAR = 1;
      DROP N;
PROC PRINT;
RUN; 





PROC FREQ DATA = HARVEST2; 
     TABLES FISHERY*PHONE;
     WEIGHT COHO;
	TITLE3 'COHO';
RUN;
PROC FREQ DATA = HARVEST2; 
     WHERE PHONE = 'N';
     TABLES FISHERY / NOPRINT OUT = CF_COHOS;
     WEIGHT COHO;
RUN;

DATA CF_COHOS; SET CF_COHOS;
      IF FISHERY = 'KENAI'   THEN DO;  P_KENAI_COHOS = PERCENT / 100;  END;
      IF FISHERY = 'KASILOF' THEN DO;  P_KASILOF_COHOS = PERCENT / 100;  END;


PROC MEANS SUM NOPRINT DATA = CF_COHOS;
      VAR P_KENAI_COHOS P_KASILOF_COHOS COUNT;
      OUTPUT OUT = CF_COHOS SUM = P_KENAI_COHOS P_KASILOF_COHOS N;

DATA CF_COHOS; SET CF_COHOS (DROP = _TYPE_ _FREQ_);
      V_P_COHOS = (P_KENAI_COHOS * (1 - P_KENAI_COHOS)) / (N - 1); 
      MERGEVAR = 1;
      DROP N;
PROC PRINT;
RUN; 



PROC FREQ DATA = HARVEST2; 
     TABLES FISHERY*PHONE;
     WEIGHT CHUM;
	TITLE3 'CHUM';
RUN;
PROC FREQ DATA = HARVEST2; 
     WHERE PHONE = 'N';
     TABLES FISHERY / NOPRINT OUT = CF_CHUMS;
     WEIGHT CHUM;
RUN;

DATA CF_CHUMS; SET CF_CHUMS;
      IF FISHERY = 'KENAI'   THEN DO;  P_KENAI_CHUMS = PERCENT / 100;  END;
      IF FISHERY = 'KASILOF' THEN DO;  P_KASILOF_CHUMS = PERCENT / 100;  END;

PROC MEANS SUM NOPRINT DATA = CF_CHUMS;
      VAR P_KENAI_CHUMS P_KASILOF_CHUMS COUNT;
      OUTPUT OUT = CF_CHUMS SUM = P_KENAI_CHUMS P_KASILOF_CHUMS N;

DATA CF_CHUMS; SET CF_CHUMS (DROP = _TYPE_ _FREQ_);
      V_P_CHUMS = (P_KENAI_CHUMS * (1 - P_KENAI_CHUMS)) / (N - 1); 
      MERGEVAR = 1;
      DROP N;
PROC PRINT;
RUN; 


PROC FREQ DATA = HARVEST2; 
     TABLES FISHERY*PHONE;
     WEIGHT FLOUNDER;
	TITLE3 'FLOUNDER';
RUN;
PROC FREQ DATA = HARVEST2;
     WHERE PHONE = 'N'; 
     TABLES FISHERY / NOPRINT OUT = CF_FLOUNDER;
     WEIGHT FLOUNDER;
RUN;

DATA CF_FLOUNDER; SET CF_FLOUNDER;
      IF FISHERY = 'KENAI'   THEN DO;  P_KENAI_FLOUNDER = PERCENT / 100;  END;
      IF FISHERY = 'KASILOF' THEN DO;  P_KASILOF_FLOUNDER = PERCENT / 100;  END;

PROC MEANS SUM NOPRINT DATA = CF_FLOUNDER;
      VAR P_KENAI_FLOUNDER P_KASILOF_FLOUNDER COUNT;
      OUTPUT OUT = CF_FLOUNDER SUM = P_KENAI_FLOUNDER P_KASILOF_FLOUNDER N;

DATA CF_FLOUNDER; SET CF_FLOUNDER (DROP = _TYPE_ _FREQ_);
      V_P_FLOUNDER = (P_KENAI_FLOUNDER * (1 - P_KENAI_FLOUNDER)) / (N - 1); 
      MERGEVAR = 1;
      DROP N;
PROC PRINT;
RUN;




DATA CF; MERGE CF_DAYS CF_REDS CF_KINGS CF_PINKS CF_COHOS CF_CHUMS CF_FLOUNDER; BY MERGEVAR;
     DROP MERGEVAR;
PROC PRINT;
     TITLE3;
RUN;

DATA SASDATA.CF_UNKNOWNS; SET CF;
RUN;
