---
title: "Tidy Data"
author: "Ben Buzzee"
date: "May 17, 2018"
output: 
  html_document: 
    fig_height: 6
    fig_width: 9
    highlight: haddock
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)



```

# Clean section

```{r }

catch_df <- read.csv(url("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/df35b.302.1",
                         method = "libcurl"),
                     stringsAsFactors = FALSE) %>% as_tibble()


# remove cols and gather
catch_df <- catch_df %>% select(-c(All, notesRegCode)) %>% gather(key = species, value = catch, -Region, -Year)

# fix input
catch_df <- catch_df %>% 
  mutate(catch = ifelse(catch == "I", yes = 1, no = catch)) %>% mutate(catch = as.integer(catch))


  

head(catch_df, 50)
        
```
# Analysis

```{r}
catch_df %>% group_by(Year, Region) %>% summarize(catch = mean(catch)) %>%  ggplot(aes(x=Year, y =catch)) + geom_point() + facet_wrap(~Region) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```






