OPTIONS PAGENO=1 NODATE SYMBOLGEN LINESIZE=119 PAGESIZE=67 ;

%LET YEAR = 2015;

LIBNAME SASDATA BASE "O:\DSF\RTS\common\Pat\PERMITS\&PROJECT\&YEAR";
TITLE1 "&PROJECT - &YEAR";

RUN;




PROC IMPORT OUT= WORK.ONE 
     DATAFILE= "O:\DSF\RTS\common\Pat\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
     DBMS=EXCEL REPLACE;
     SHEET="HARVEST_BY_PERMIT$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
PROC PRINT DATA = ONE (OBS = 50);
RUN;

DATA ONE; SET ONE; *HARVEST_BY_PERMIT;
     IF SALMON = 0 THEN DO;
        RED = 0;
        KING = 0;
        COHO = 0;
        PINK = 0;
        CHUM = 0;
     END;
     KEEP PERMIT ALLOWED TRIPS RED KING COHO PINK CHUM SALMON;

PROC SORT; BY PERMIT;
PROC PRINT DATA = ONE (OBS = 50);
     TITLE2 'DATA ONE';
RUN;


PROC IMPORT OUT= WORK.TWO
     DATAFILE= "O:\DSF\RTS\common\Pat\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
     DBMS=EXCEL REPLACE;
     SHEET="HARVEST_BY_PERMIT_AND_FISHERY$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
PROC PRINT DATA = TWO (OBS = 50);
RUN;


DATA TWO; SET TWO; *HARVEST_BY_PERMIT_FISHERY;
     KEEP PERMIT FISHERY DAYS RED KING COHO PINK CHUM;

PROC SORT; BY PERMIT;
PROC PRINT DATA = TWO (OBS = 50);
     TITLE2 'DATA TWO';
RUN;



PROC IMPORT OUT= WORK.THREE
     DATAFILE= "O:\DSF\RTS\common\Pat\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
     DBMS=EXCEL REPLACE;
     SHEET="FISHERIES_BY_PERMIT$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
PROC PRINT DATA = THREE (OBS = 50);
RUN;


DATA THREE; SET THREE; *FISHERIES;
     KEEP PERMIT FISHERY1 FISHERY2 FISHERY3 FISHERIES;

PROC SORT; BY PERMIT;
PROC PRINT DATA = THREE (OBS = 50);
     TITLE2 'DATA THREE';
RUN;


DATA TWO; SET TWO;
     SALMON = SUM(OF RED KING COHO PINK CHUM);
DATA KENAI; SET TWO;
     IF FISHERY = 'KENAI';
     KENAI_HARVEST = SALMON;
     KENAI_DAYS = DAYS;
     KEEP PERMIT KENAI_HARVEST KENAI_DAYS;
DATA KASILOF_DIPNET; SET TWO;
     IF FISHERY = 'KASILOF DIPNET';
     KASILOF_DIPNET_HARVEST = SALMON;
     KASILOF_DIPNET_DAYS = DAYS;
     KEEP PERMIT KASILOF_DIPNET_HARVEST KASILOF_DIPNET_DAYS;
DATA KASILOF_GILLNET; SET TWO;
     IF FISHERY = 'KASILOF GILLNET';
     KASILOF_GILLNET_HARVEST = SALMON;
     KASILOF_GILLNET_DAYS = DAYS;
     KEEP PERMIT KASILOF_GILLNET_HARVEST KASILOF_GILLNET_DAYS;
DATA FISH_CREEK; SET TWO;
     IF FISHERY = 'FISH CREEK';
     FISH_CREEK_HARVEST = SALMON;
     FISH_CREEK_DAYS = DAYS;
     KEEP PERMIT FISH_CREEK_HARVEST FISH_CREEK_DAYS;
DATA UNKNOWN; SET TWO;
     IF FISHERY = 'UNKNOWN';
     UNKNOWN_HARVEST = SALMON;
     UNKNOWN_DAYS = DAYS;
     KEEP PERMIT UNKNOWN_HARVEST UNKNOWN_DAYS;

DATA FISHERY_HARVEST; MERGE KENAI KASILOF_DIPNET KASILOF_GILLNET FISH_CREEK UNKNOWN; BY PERMIT;
PROC PRINT DATA = FISHERY_HARVEST (OBS = 50);
RUN;


DATA ALL; MERGE ONE THREE FISHERY_HARVEST; BY PERMIT;
     IF KENAI_HARVEST = . THEN DO; KENAI_HARVEST = 0; KENAI_DAYS = 0; END;
     IF KASILOF_DIPNET_HARVEST = . THEN DO; KASILOF_DIPNET_HARVEST = 0; KASILOF_DIPNET_DAYS = 0; END;
     IF KASILOF_GILLNET_HARVEST = . THEN DO; KASILOF_GILLNET_HARVEST = 0; KASILOF_GILLNET_DAYS = 0; END;
     IF FISH_CREEK_HARVEST = . THEN DO; FISH_CREEK_HARVEST = 0; FISH_CREEK_DAYS = 0; END;
     IF UNKNOWN_HARVEST = . THEN DO; UNKNOWN_HARVEST = 0; UNKNOWN_DAYS = 0; END;
     IF FISHERIES = . THEN FISHERIES = 0;
     TOTAL_DAYS = KENAI_DAYS + KASILOF_DIPNET_DAYS + KASILOF_GILLNET_DAYS + FISH_CREEK_DAYS + UNKNOWN_DAYS;
     HOUSEHOLD_SIZE = ((ALLOWED - 25) / 10) + 1;
     YEAR = &YEAR *1;
     DROP FISHERY1 FISHERY2 FISHERY3;

DATA ALL2; 
     RETAIN YEAR PERMIT ALLOWED RED KING COHO PINK CHUM SALMON FISHERIES KENAI_HARVEST KENAI_DAYS KASILOF_DIPNET_HARVEST 
            KASILOF_DIPNET_DAYS KASILOF_GILLNET_HARVEST KASILOF_GILLNET_DAYS FISH_CREEK_HARVEST FISH_CREEK_DAYS UNKNOWN_HARVEST UNKNOWN_DAYS 
            TOTAL_DAYS HOUSEHOLD_SIZE;
     SET ALL;
PROC PRINT DATA = ALL2 (OBS = 50);
RUN;

PROC MEANS SUM;
     VAR KENAI_HARVEST KASILOF_DIPNET_HARVEST KASILOF_GILLNET_HARVEST FISH_CREEK_HARVEST UNKNOWN_HARVEST;
RUN;

DATA SASDATA.EXTRA&YEAR; SET ALL2;
RUN;


********************************************************************************************************************************************;
*         NEED TO COPY/MOVE SASDATA.EXTRA20XX FROM THE YEAR FOLDER TO THE REPORT FOLDER BEFORE RUNNING THE REST OF THIS PROGRAM            *;
********************************************************************************************************************************************;

/*
%LET YEAR1 = 2013;
%LET YEAR2 = 2014;
%LET YEAR3 = 2015;

LIBNAME SASDATA BASE "O:\DSF\RTS\common\Pat\Permits\Salmon\REPORT &YEAR1-&YEAR3";
RUN;

DATA EXTRA&YEAR1&YEAR2&YEAR3; SET SASDATA.EXTRA&YEAR1 SASDATA.EXTRA&YEAR2 SASDATA.EXTRA&YEAR3;
     IF FISH_CREEK_HARVEST = . THEN DO; FISH_CREEK_HARVEST = 0; FISH_CREEK_DAYS = 0; END;
     PERCENT_ALLOWED = ROUND((SALMON / ALLOWED) * 100,1);
     EXTRA = 1;
     DROP TRIPS;
PROC SORT; BY YEAR PERMIT;
RUN;
proc contents;
run;
PROC PRINT DATA = EXTRA&YEAR1&YEAR2&YEAR3 (OBS = 1000);
RUN;

LIBNAME SASDATA BASE "O:\DSF\RTS\common\Pat\Permits\Salmon\&YEAR1";
DATA PERSONAL&YEAR1; SET SASDATA.PERSONAL;
     LENGTH C $19;
     YEAR = &YEAR1*1;
     KEEP YEAR PERMIT CITY C;

DATA PERSONAL&YEAR1; SET PERSONAL&YEAR1;
     C = CITY;
     DROP CITY;
RUN;

LIBNAME SASDATA BASE "O:\DSF\RTS\common\Pat\Permits\Salmon\&YEAR2";
DATA PERSONAL&YEAR2; SET SASDATA.PERSONAL;
     LENGTH C $19;
     YEAR = &YEAR2*1;
     KEEP YEAR PERMIT CITY C;

DATA PERSONAL&YEAR2; SET PERSONAL&YEAR2;
     C = CITY;
     DROP CITY;
RUN;

LIBNAME SASDATA BASE "O:\DSF\RTS\common\Pat\Permits\Salmon\&YEAR3";
DATA PERSONAL&YEAR3; SET SASDATA.PERSONAL;
     LENGTH C $19;
     YEAR = &YEAR3*1;
     KEEP YEAR PERMIT CITY C;

DATA PERSONAL&YEAR3; SET PERSONAL&YEAR3;
     C = CITY;
     DROP CITY;
RUN;

DATA PERSONAL; SET PERSONAL&YEAR1 PERSONAL&YEAR2 PERSONAL&YEAR3;
     RENAME C = CITY;
     PERSONAL = 1;
PROC SORT; BY YEAR PERMIT;
RUN;



DATA EXTRA&YEAR1&YEAR2&YEAR3; MERGE EXTRA&YEAR1&YEAR2&YEAR3 PERSONAL; BY YEAR PERMIT;
     IF EXTRA = 1;
PROC SORT; BY CITY;
RUN; 
PROC PRINT DATA = EXTRA&YEAR1&YEAR2&YEAR3 (OBS = 1000);
RUN;










LIBNAME SASDATA BASE "O:\DSF\RTS\common\Pat\Permits\Salmon";
DATA CITY; SET SASDATA.CITIES;
PROC SORT; BY CITY;
PROC PRINT;
RUN;

DATA EXTRA&YEAR1&YEAR2&YEAR3; MERGE CITY EXTRA&YEAR1&YEAR2&YEAR3; BY CITY;
     IF EXTRA = 1;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;
     DROP EXTRA;

DATA EXTRA&YEAR1&YEAR2&YEAR3; SET EXTRA&YEAR1&YEAR2&YEAR3;
     IF CITY = ' ' THEN REGION = 4;
     DROP NEW_NAME PERSONAL;
RUN;


PROC SORT DATA = EXTRA&YEAR1&YEAR2&YEAR3; BY YEAR PERMIT;
PROC PRINT DATA = EXTRA&YEAR1&YEAR2&YEAR3 (OBS = 1000);
RUN;

PROC CONTENTS DATA = EXTRA&YEAR1&YEAR2&YEAR3;
RUN;

DATA EXTRA&YEAR1&YEAR2&YEAR3_B; SET EXTRA&YEAR1&YEAR2&YEAR3;
DATA EXTRA&YEAR1&YEAR2&YEAR3; 
     RETAIN YEAR PERMIT CITY REGION AREA ALLOWED RED KING COHO PINK CHUM SALMON 
            PERCENT_ALLOWED FISHERIES KENAI_HARVEST KENAI_DAYS KASILOF_DIPNET_HARVEST KASILOF_DIPNET_DAYS 
            KASILOF_GILLNET_HARVEST KASILOF_GILLNET_DAYS FISH_CREEK_HARVEST FISH_CREEK_DAYS 
            UNKNOWN_HARVEST UNKNOWN_DAYS TOTAL_DAYS HOUSEHOLD_SIZE;
     SET EXTRA&YEAR1&YEAR2&YEAR3_B;
PROC PRINT DATA = EXTRA&YEAR1&YEAR2&YEAR3 (OBS = 100);
RUN;


DATA EXPORT1; SET EXTRA&YEAR1&YEAR2&YEAR3;
     IF FISHERIES GE 0;
PROC EXPORT DATA= EXPORT1 
     OUTFILE= "O:\DSF\RTS\common\Pat\Permits\Salmon\REPORT &YEAR1-&YEAR3\MORE EXTRA ESTIMATES.xls" 
     DBMS=EXCEL REPLACE;
     SHEET="DATA FISHERIES GE 0"; 
RUN;

DATA EXPORT2; SET EXTRA&YEAR1&YEAR2&YEAR3;
     IF FISHERIES EQ 1;
PROC EXPORT DATA= EXPORT2 
     OUTFILE= "O:\DSF\RTS\common\Pat\Permits\Salmon\REPORT &YEAR1-&YEAR3\MORE EXTRA ESTIMATES.xls" 
     DBMS=EXCEL REPLACE;
     SHEET="DATA FISHERIES EQ 1"; 
RUN;

DATA EXPORT3; SET EXTRA&YEAR1&YEAR2&YEAR3;
     IF FISHERIES GE 1;
PROC EXPORT DATA= EXPORT3 
     OUTFILE= "O:\DSF\RTS\common\Pat\Permits\Salmon\REPORT &YEAR1-&YEAR3\MORE EXTRA ESTIMATES.xls" 
     DBMS=EXCEL REPLACE;
     SHEET="DATA FISHERIES GE 1"; 
RUN;

*/

/*
PROC DATASETS KILL;
RUN;
*/



/*
PROC IMPORT OUT= WORK.CHECK DATAFILE= "O:\DSF\RTS\Pat\Permits\Salmon\REPORT 2007-2009\MORE EXTRA ESTIMATES2.xlsx" DBMS=EXCEL REPLACE;
     RANGE="'DATA FISHERIES GE 1$'"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;

PROC PRINT DATA = CHECK (OBS = 50);
RUN;


PROC SORT; BY YEAR;
PROC MEANS SUM; BY YEAR;
     VAR SALMON;
RUN;
*/
