OPTIONS PAGENO=1 NODATE SYMBOLGEN LINESIZE=119 PAGESIZE=67 ;
%LET PROJECT = SALMON;
%LET YEAR = 2015;


LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR";
RUN;

DATA DID_NOT_FISH; SET SASDATA.ISSUED;
     IF STATUS = 'DID NOT FISH';
     KEEP PERMIT STATUS FAMILYSI ALLOWED;

DATA PERSONAL; SET SASDATA.PERSONAL;
     KEEP PERMIT CITY;

DATA PERSONAL;
     LENGTH CITY$19.;
     SET PERSONAL;

DATA PERSONAL2; MERGE PERSONAL DID_NOT_FISH; BY PERMIT;
     IF STATUS = 'DID NOT FISH';
PROC SORT DATA = PERSONAL2; BY CITY;

DATA CITY; SET SASDATA.CITIES;
PROC CONTENTS;
RUN;
PROC SORT DATA = CITY; BY CITY;

DATA LOCATION; MERGE CITY PERSONAL2; BY CITY;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;
     IF PERMIT = . THEN DELETE;

DATA LOCATION; SET LOCATION;
     IF CITY = ' ' THEN REGION = 4;
     DROP NEW_NAME;
	 YEAR = &YEAR *1;

DATA LOCATION2; 
     RETAIN YEAR CITY REGION AREA PERMIT familysi allowed STATUS;
     SET LOCATION;

PROC EXPORT DATA= WORK.LOCATION2
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\REPORT 2013-2015\DID NOT FISH.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="&YEAR"; 
RUN;












