%LET PROJECT = SALMON;
%LET PROGRAM = EXTRA ESTIMATES;
%LET YEAR = 2009;
%LET SPECIES = SALMON;
%LET SPECIES_COMMA = RED,KING,COHO,PINK,CHUM,FLOUNDER; 
%LET SPECIES_LIST = RED KING COHO PINK CHUM FLOUNDER; 

%LET GILLNET_START = '15JUN09'D; 
%LET GILLNET_STOP = '24JUN09'D; 
RUN;

TITLE1 "&PROJECT - &YEAR";

OPTIONS PAGENO=1 NODATE SYMBOLGEN LINESIZE=119 PAGESIZE=67 ;
LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR";
RUN;



PROC SORT DATA=SASDATA.SALMON_HARVEST; BY PERMIT; RUN;  
PROC SORT DATA=SASDATA.ISSUED; BY PERMIT; RUN;

DATA ALLPERMITS; MERGE SASDATA.SALMON_HARVEST SASDATA.ISSUED ; BY PERMIT;  
RUN;

DATA ALLPERMITS2; MERGE ALLPERMITS SASDATA.PERSONAL; BY PERMIT;
     RENAME FISHERY = LOCATION;
     DROP ADLNO FAMILYSI SPECIES OFFICE VENDORCOPY;

DATA ALLPERMITS3; SET ALLPERMITS2;
     IF RESPONDED = 'Y' AND STATUS EQ 'HARVEST REPORTED';
     IF LOCATION EQ 'KASILOF' AND HARVDATE GE &GILLNET_START AND HARVDATE LE &GILLNET_STOP THEN FISHERY = 'KASILOF GILLNET';  *GILLNET;
     IF LOCATION EQ 'KASILOF' AND FISHERY = '' THEN FISHERY = 'KASILOF DIPNET';  *DIPNET;
     IF LOCATION EQ 'UNK FIXABLE' THEN FISHERY = 'UNKNOWN';
     IF LOCATION EQ 'UNK' THEN FISHERY = 'UNKNOWN';
     IF FISHERY = '' THEN FISHERY = LOCATION;
     DROP LOCATION;
RUN;

PROC SORT DATA = ALLPERMITS3; BY FISHERY;
PROC FREQ DATA = ALLPERMITS3; BY FISHERY;
     TABLES CITY / OUT = DAYS_BY_FISHERY_AND_PERMIT_CITY;
     TITLE2 'TRIPS BY CITY AND FISHERY';
RUN;

PROC PRINT DATA=FISHERY_BY_CITY;RUN;

DATA DAYS_BY_FISHERY_AND_PERMIT_CITY; SET DAYS_BY_FISHERY_AND_PERMIT_CITY;
     RENAME COUNT = DAYS;

PROC SORT DATA=DAYS_BY_FISHERY_AND_PERMIT_CITY; BY CITY;
DATA DAYS_BY_FISHERY_AND_PERMIT_CITY; MERGE DAYS_BY_FISHERY_AND_PERMIT_CITY SASDATA.CITIES; BY CITY;
     IF FISHERY = '' THEN DELETE;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;
     DROP NEW_NAME;
RUN;

PROC SORT DATA = DAYS_BY_FISHERY_AND_PERMIT_CITY; BY FISHERY CITY;
PROC PRINT DATA = DAYS_BY_FISHERY_AND_PERMIT_CITY (OBS = 50);
     TITLE2 'DAYS BY FISHERY AND PERMIT CITY';
RUN;


PROC FREQ DATA = ALLPERMITS3; 
     TABLES PERMIT*FISHERY / NOPRINT OUT = FISHERY_BY_PERMIT;
     TITLE2 'FISHERY BY PERMIT';
RUN;


DATA FISHERY_BY_PERMIT_1; SET FISHERY_BY_PERMIT; BY PERMIT FISHERY;
     IF FIRST.PERMIT;
     F1 = 1;
     RENAME FISHERY = FISHERY1;

DATA FISHERY_BY_PERMIT_2; SET FISHERY_BY_PERMIT; BY PERMIT FISHERY;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_2; SET FISHERY_BY_PERMIT_2; BY PERMIT FISHERY;
     IF FIRST.PERMIT;
     F2 = 1;
     RENAME FISHERY = FISHERY2;

DATA FISHERY_BY_PERMIT_3; SET FISHERY_BY_PERMIT; BY PERMIT FISHERY;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_3; SET FISHERY_BY_PERMIT_3; BY PERMIT FISHERY;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_3; SET FISHERY_BY_PERMIT_3; BY PERMIT;
     IF FIRST.PERMIT;
     F3 = 1;
     RENAME FISHERY = FISHERY3;

DATA FISHERY_BY_PERMIT_4; SET FISHERY_BY_PERMIT; BY PERMIT;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_4; SET FISHERY_BY_PERMIT_4; BY PERMIT;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_4; SET FISHERY_BY_PERMIT_4; BY PERMIT;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_4; SET FISHERY_BY_PERMIT_4; BY PERMIT;
     IF FIRST.PERMIT;
     F4 = 1;
     RENAME FISHERY = FISHERY4;


DATA FISHERIES; MERGE FISHERY_BY_PERMIT_1 FISHERY_BY_PERMIT_2 FISHERY_BY_PERMIT_3 FISHERY_BY_PERMIT_4;
     BY PERMIT;
     FISHERIES = SUM(OF F1  F2  F3  F4);
     DROP COUNT PERCENT F1 F2 F3 F4 FISHERY4;
RUN;

PROC FREQ;
     TABLES FISHERIES / OUT = FISHERIES_FREQ;
     TITLE2 'FREQ OF FISHERIES BY PERMIT';
RUN;

     

PROC SORT DATA = ALLPERMITS3; BY PERMIT FISHERY;
PROC MEANS SUM NOPRINT DATA = ALLPERMITS3; BY PERMIT FISHERY;
     VAR &SPECIES_LIST;
     OUTPUT OUT = HARVEST_BY_PERMIT_FISHERY SUM = RED KING COHO PINK CHUM FLOUNDER;

DATA HARVEST_BY_PERMIT_FISHERY; SET HARVEST_BY_PERMIT_FISHERY;
     RENAME _FREQ_ = DAYS;
     DROP _TYPE_ FLOUNDER;
PROC PRINT DATA = HARVEST_BY_PERMIT_FISHERY (OBS = 50);
     TITLE2 'HARVEST BY PERMIT FISHERY';
RUN;

PROC SORT DATA = ALLPERMITS3; BY CITY;
PROC MEANS SUM NOPRINT DATA = ALLPERMITS3; BY CITY;
     VAR &SPECIES_LIST;
     OUTPUT OUT = HARVEST_BY_CITY SUM = RED KING COHO PINK CHUM FLOUNDER;

DATA HARVEST_BY_CITY; SET HARVEST_BY_CITY;
     RENAME _FREQ_ = TRIPS;
     SALMON = SUM(OF RED KING COHO PINK CHUM);
     IF SALMON = . THEN SALMON = 0; 
     DROP _TYPE_ FLOUNDER;

PROC SORT DATA=HARVEST_BY_CITY; BY CITY;
DATA HARVEST_BY_CITY; MERGE HARVEST_BY_CITY SASDATA.CITIES; BY CITY;
     IF TRIPS = . THEN DELETE;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;
     DROP NEW_NAME;
RUN;

PROC PRINT DATA = HARVEST_BY_CITY (OBS = 50);
     TITLE2 'HARVEST BY CITY';
RUN;


PROC SORT DATA = ALLPERMITS3; BY PERMIT ALLOWED;
PROC MEANS SUM NOPRINT DATA = ALLPERMITS3; BY PERMIT ALLOWED;
     VAR &SPECIES_LIST;
     OUTPUT OUT = HARVEST_BY_PERMIT SUM = RED KING COHO PINK CHUM FLOUNDER;

DATA HARVEST_BY_PERMIT; SET HARVEST_BY_PERMIT;
     RENAME _FREQ_ = TRIPS;
     SALMON = SUM(OF RED KING COHO PINK CHUM);
     IF SALMON = . THEN SALMON = 0; 
     PERCENT_ALLOWED = ROUND((SALMON/ALLOWED)*100,1);
     DROP _TYPE_ FLOUNDER;
PROC PRINT DATA = HARVEST_BY_PERMIT (OBS = 50);
     TITLE2 'HARVEST BY PERMIT';
RUN;

PROC FREQ DATA = HARVEST_BY_PERMIT;
     TABLES PERCENT_ALLOWED;
     TITLE2 'PERCENT OF ALLOWED';
RUN;

DATA CHECK; SET HARVEST_BY_PERMIT;
     IF PERCENT_ALLOWED = .;
     TITLE2 'THESE PERMITS DO NOT HAVE A LIMIT';
PROC PRINT;
RUN;

DATA CHECK2; SET HARVEST_BY_PERMIT;
     IF PERCENT_ALLOWED GT 100;
     TITLE2 'THESE PERMITS ARE OVER THE LIMIT';
PROC PRINT;
RUN;


PROC SORT DATA = ALLPERMITS3; BY HARVDATE FISHERY;
PROC MEANS DATA = ALLPERMITS3 SUM NOPRINT; BY HARVDATE FISHERY;
     ID MONTH DAY;
     VAR RED PINK COHO CHUM KING FLOUNDER;
     OUTPUT OUT = DAILY SUM = SUM_RED SUM_PINK SUM_COHO SUM_CHUM SUM_KING SUM_FLOUNDER
                        MEAN = MEAN_RED MEAN_PINK MEAN_COHO MEAN_CHUM MEAN_KING MEAN_FLOUNDER
                        STDERR = STDERR_RED STDERR_PINK STDERR_COHO STDERR_CHUM STDERR_KING STDERR_FLOUNDER
                        N = TRIPS;


DATA DAILY; SET DAILY (DROP= _TYPE_ _FREQ_);
     YEAR = YEAR(HARVDATE);
     IF YEAR = . THEN YEAR = 1990;
     DROP MONTH DAY YEAR;

PROC SORT; BY FISHERY HARVDATE;
PROC PRINT DATA = DAILY (OBS = 25);
     TITLE2 'DAILY HARVEST ESTIMATES';

RUN;

PROC PRINT DATA = ALLPERMITS3 (OBS = 50);
RUN;



PROC EXPORT DATA= WORK.DAYS_BY_FISHERY_AND_PERMIT_CITY
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="DAYS BY FISHERY AND PERMIT CITY"; 
RUN;

PROC EXPORT DATA= WORK.HARVEST_BY_PERMIT_FISHERY
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="HARVEST BY PERMIT AND FISHERY"; 
RUN;

PROC EXPORT DATA= WORK.HARVEST_BY_CITY
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="HARVEST BY CITY"; 
RUN;

PROC EXPORT DATA= WORK.HARVEST_BY_PERMIT
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="HARVEST BY PERMIT"; 
RUN;


PROC EXPORT DATA= WORK.DAILY
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="DAILY HARVEST BY FISHERY"; 
RUN;

PROC EXPORT DATA= WORK.FISHERIES
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="FISHERIES BY PERMIT"; 
RUN;


PROC EXPORT DATA= WORK.FISHERIES_FREQ
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="NUMBER OF FISHERIES SUMMARY"; 
RUN;






******************************************************************************************************************************;
*     THE FOLLOWING PART OF THE PROGRAM ESTIMATES REPORTED HARVEST BY FISHERY, REGION AND AREA                               *;
*     REGION AND AREA WERE DEFINED BY KRISSY IN THE SPREADSHEET O:\DSF\RTS\Pat\Permits\Salmon\CITIES 2007 - 2008_KD.xls      *;
*     AND WERE TRANSLATED INTO SAS IN THE PROGRAM O:\DSF\RTS\Pat\Permits\Salmon\CITIES.SAS                                   *;
*     AND STORED AS A PERMANENT SASDATABASE O:\DSF\RTS\Pat\Permits\Salmon\CITIES.SAS                                         *;
*                                                                                                                            *;
*     THESE ESTIMATES WERE REQUESTED BY KRISSY IN JAN 2010.  SHE WANTED THE ESTIMATES FOR ALL SPECIES 2007 - 2008            *;
******************************************************************************************************************************;

DATA HARVESTED; SET SASDATA.HARVESTED; 
     HARVFILE = 1;
     SALMON = red + king + coho + pink + chum;
     RENAME FISHERY = F;
     DROP HARVDATE FAMILYSI MAILING COMPLIANT FLOUNDER TOTAL;
DATA HARVESTED; SET HARVESTED;
     IF F = 1 THEN FISHERY = 'KENAI          ';
     IF F = 2 THEN FISHERY = 'KASILOF DIPNET';
     IF F = 3 THEN FISHERY = 'KASILOF GILLNET';
     IF F = 4 THEN FISHERY = 'FISH CREEK';
     IF F = 5 THEN FISHERY = 'UNK FIXABLE';
     IF F = 6 THEN FISHERY = 'UNKNOWN';
     IF F = 7 THEN FISHERY = 'TOTAL';
PROC SORT; BY PERMIT;



DATA PERSONAL; SET SASDATA.PERSONAL;
     LENGTH C $19;
     KEEP PERMIT CITY C;
DATA PERSONAL; SET PERSONAL;
     C = CITY;
     DROP CITY;
DATA PERSONAL; SET PERSONAL;
     RENAME C = CITY;
PROC SORT DATA = PERSONAL; BY PERMIT;


DATA REPORTED; MERGE HARVESTED PERSONAL; BY PERMIT;
     IF HARVFILE = 1;
PROC SORT; BY CITY;


DATA CITY; SET SASDATA.CITIES;

PROC SORT; BY CITY;


DATA LOCATION; MERGE CITY REPORTED; BY CITY;
     IF HARVFILE = 1;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;
     DROP HARVFILE;

DATA LOCATION; SET LOCATION;
     IF CITY = ' ' THEN REGION = 4;
     DROP NEW_NAME;


PROC SORT; BY REGION AREA;
PROC SUMMARY NWAY DATA = LOCATION; BY REGION AREA;
     CLASS FISHERY;
     ID F;
     VAR RED KING COHO PINK CHUM SALMON;
     OUTPUT OUT = LOCATIONHARVEST N=DAYS SUM=RED KING COHO PINK CHUM SALMON;
RUN;

DATA LOCATIONHARVEST; SET LOCATIONHARVEST;
     DROP _TYPE_ _FREQ_;
PROC SORT; BY REGION AREA F;
PROC PRINT;
     FORMAT _NUMERIC_ COMMA9.;
     VAR REGION AREA FISHERY DAYS RED KING COHO PINK CHUM SALMON;
RUN;

PROC EXPORT DATA= WORK.LOCATIONHARVEST
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="HARVEST BY REGION AREA"; 
RUN;


DATA PERSONAL; SET SASDATA.PERSONAL;
     KEEP PERMIT CITY;
PROC FREQ;
     TABLES CITY / NOPRINT MISSING OUT=PERMIT_CITY;

DATA PERMIT_CITY; SET PERMIT_CITY;
     RENAME COUNT = NUMBER_PERMITS;
     DROP PERCENT;
PROC PRINT;
     TITLE2 'RESIDENCE OF PERMIT HOLDERS';
RUN;

DATA LOCATION2; MERGE CITY PERMIT_CITY; BY CITY;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;

DATA LOCATION2; SET LOCATION2;
     IF NUMBER_PERMITS = . THEN DELETE;
     IF CITY = ' ' THEN REGION = 4;
     DROP NEW_NAME;

PROC SORT DATA = LOCATION2; BY REGION;
PROC FREQ DATA = LOCATION2; BY REGION;
     TABLES AREA /  MISSING OUT=LOCATIONPERMIT;
     WEIGHT NUMBER_PERMITS;

DATA LOCATIONPERMIT; SET LOCATIONPERMIT;
     RENAME COUNT = NUMBER_PERMITS;
     DROP PERCENT;

PROC PRINT;
RUN;

PROC EXPORT DATA= WORK.LOCATIONPERMIT
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="PERMITS BY REGION AREA"; 
RUN;



************************************************************************************************************;
*                  SAME AS ABOVE BUT FOR THOSE THAT DID NOT FISH                                           *;
************************************************************************************************************;
DATA DID_NOT_FISH; SET SASDATA.ISSUED;
     IF STATUS = 'DID NOT FISH';
     KEEP PERMIT STATUS;

DATA PERSONAL; SET SASDATA.PERSONAL;
     KEEP PERMIT CITY;

DATA PERSONAL2; MERGE PERSONAL DID_NOT_FISH; BY PERMIT;
     IF STATUS = 'DID NOT FISH';
     TITLE3 'ONLY INCLUDES THOSE PERMITS THAT DID NOT FISH';

PROC FREQ;
     TABLES CITY / NOPRINT MISSING OUT=PERMIT_CITY;

DATA PERMIT_CITY; SET PERMIT_CITY;
     RENAME COUNT = NUMBER_PERMITS;
     DROP PERCENT;
PROC PRINT;
     TITLE2 'RESIDENCE OF PERMIT HOLDERS';
RUN;

DATA LOCATION3; MERGE CITY PERMIT_CITY; BY CITY;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;

DATA LOCATION3; SET LOCATION3;
     IF NUMBER_PERMITS = . THEN DELETE;
     IF CITY = ' ' THEN REGION = 4;
     DROP NEW_NAME;

PROC SORT DATA = LOCATION3; BY REGION;
PROC FREQ DATA = LOCATION3; BY REGION;
     TABLES AREA /  MISSING OUT=LOCATIONPERMIT;
     WEIGHT NUMBER_PERMITS;

DATA LOCATIONPERMIT; SET LOCATIONPERMIT;
     RENAME COUNT = NUMBER_PERMITS;
     DROP PERCENT;

PROC PRINT;
RUN;

PROC EXPORT DATA= WORK.LOCATIONPERMIT
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="DID NOT FISH BY REGION AREA"; 
RUN;


************************************************************************************************************;
*           THIS ANALYSIS IS LIMITED TO THOSE PERMITS THAT ONLY FISHED IN ONE FISHERY                      *;
*                  IT IS USED TO MAKE FIGURE 6 IN THE FDS REPORT                                           *;
************************************************************************************************************;

DATA ONEFISHERY; SET FISHERIES;
     IF FISHERIES = 1;
     FISHERY = FISHERY1;
     KEEP PERMIT FISHERY;
PROC SORT; BY PERMIT;

DATA ONEFISHERY; MERGE ONEFISHERY PERSONAL; BY PERMIT;
     IF FISHERY NE '';
PROC SORT; BY CITY;

DATA PERMIT_REGION2; MERGE ONEFISHERY CITY; BY CITY;
     IF REGION = 2;
     IF FISHERY NE '';

PROC SORT; BY FISHERY;
PROC FREQ; BY FISHERY;
     TABLES AREA / OUT=FIGURE6;
RUN;

PROC PRINT DATA = FIGURE6;
     TITLE3 'DATA IS LIMITED TO THOSE PERMITS THAT ONLY FISHED IN ONE FISHERY';
RUN;

PROC EXPORT DATA= WORK.FIGURE6
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="FIGURE 6"; 
RUN;


/*
PROC SORT DATA = ONEFISHERY; BY FISHERY;
PROC FREQ DATA = ONEFISHERY; BY FISHERY;
     TABLES CITY / OUT = FISHERY_BY_CITY2;
     TITLE2 'TRIPS BY CITY AND FISHERY';
RUN;

PROC SORT DATA = FISHERY_BY_CITY2; BY CITY;
DATA FISHERY_BY_CITY2; MERGE FISHERY_BY_CITY2 CITY; BY CITY;
     IF FISHERY = '' THEN DELETE;
PROC SORT DATA = FISHERY_BY_CITY2; BY FISHERY CITY;
PROC PRINT;
RUN;

PROC EXPORT DATA= WORK.FISHERY_BY_CITY2
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR EXTRA ESTIMATES" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="FISHERY BY CITY ONE FISHERY"; 
RUN;
*/
