OPTIONS PAGENO=1 NODATE SYMBOLGEN LINESIZE=119 PAGESIZE=67 ;
LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\SALMON\2010";

TITLE1 "SALMON - 2010";

RUN;




PROC IMPORT OUT= WORK.ONE 
     DATAFILE= "O:\DSF\RTS\PAT\Permits\Salmon\2010\PU PERMITS 2010 EXTRA ESTIMATES.XLS" 
     DBMS=EXCEL REPLACE;
     SHEET="HARVEST_BY_PERMIT$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
PROC PRINT DATA = ONE (OBS = 50);
RUN;

DATA ONE; SET ONE; *HARVEST_BY_PERMIT;
     IF SALMON = 0 THEN DO;
        RED = 0;
        KING = 0;
        COHO = 0;
        PINK = 0;
        CHUM = 0;
     END;
     KEEP PERMIT ALLOWED TRIPS RED KING COHO PINK CHUM SALMON;

PROC SORT; BY PERMIT;
PROC PRINT DATA = ONE (OBS = 50);
     TITLE2 'DATA ONE';
RUN;


PROC IMPORT OUT= WORK.TWO
     DATAFILE= "O:\DSF\RTS\PAT\Permits\Salmon\2010\PU PERMITS 2010 EXTRA ESTIMATES.XLS" 
     DBMS=EXCEL REPLACE;
     SHEET="HARVEST_BY_PERMIT_AND_FISHERY$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
PROC PRINT DATA = TWO (OBS = 50);
RUN;


DATA TWO; SET TWO; *HARVEST_BY_PERMIT_FISHERY;
     KEEP PERMIT FISHERY DAYS RED KING COHO PINK CHUM;

PROC SORT; BY PERMIT;
PROC PRINT DATA = TWO (OBS = 50);
     TITLE2 'DATA TWO';
RUN;



PROC IMPORT OUT= WORK.THREE
     DATAFILE= "O:\DSF\RTS\PAT\Permits\Salmon\2010\PU PERMITS 2010 EXTRA ESTIMATES.XLS" 
     DBMS=EXCEL REPLACE;
     SHEET="FISHERIES_BY_PERMIT$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
PROC PRINT DATA = THREE (OBS = 50);
RUN;


DATA THREE; SET THREE; *FISHERIES;
     KEEP PERMIT FISHERY1 FISHERY2 FISHERY3 FISHERIES;

PROC SORT; BY PERMIT;
PROC PRINT DATA = THREE (OBS = 50);
     TITLE2 'DATA THREE';
RUN;


DATA TWO; SET TWO;
     SALMON = SUM(OF RED KING COHO PINK CHUM);
DATA KENAI; SET TWO;
     IF FISHERY = 'KENAI';
     KENAI_HARVEST = SALMON;
     KENAI_DAYS = DAYS;
     KEEP PERMIT KENAI_HARVEST KENAI_DAYS;
DATA KASILOF_DIPNET; SET TWO;
     IF FISHERY = 'KASILOF DIPNET';
     KASILOF_DIPNET_HARVEST = SALMON;
     KASILOF_DIPNET_DAYS = DAYS;
     KEEP PERMIT KASILOF_DIPNET_HARVEST KASILOF_DIPNET_DAYS;
DATA KASILOF_GILLNET; SET TWO;
     IF FISHERY = 'KASILOF GILLNET';
     KASILOF_GILLNET_HARVEST = SALMON;
     KASILOF_GILLNET_DAYS = DAYS;
     KEEP PERMIT KASILOF_GILLNET_HARVEST KASILOF_GILLNET_DAYS;
DATA FISH_CREEK; SET TWO;
     IF FISHERY = 'FISH CREEK';
     FISH_CREEK_HARVEST = SALMON;
     FISH_CREEK_DAYS = DAYS;
     KEEP PERMIT FISH_CREEK_HARVEST FISH_CREEK_DAYS;
DATA UNKNOWN; SET TWO;
     IF FISHERY = 'UNKNOWN';
     UNKNOWN_HARVEST = SALMON;
     UNKNOWN_DAYS = DAYS;
     KEEP PERMIT UNKNOWN_HARVEST UNKNOWN_DAYS;

DATA FISHERY_HARVEST; MERGE KENAI KASILOF_DIPNET KASILOF_GILLNET FISH_CREEK UNKNOWN; BY PERMIT;
PROC PRINT DATA = FISHERY_HARVEST (OBS = 50);
RUN;


DATA ALL; MERGE ONE THREE FISHERY_HARVEST; BY PERMIT;
     IF KENAI_HARVEST = . THEN DO; KENAI_HARVEST = 0; KENAI_DAYS = 0; END;
     IF KASILOF_DIPNET_HARVEST = . THEN DO; KASILOF_DIPNET_HARVEST = 0; KASILOF_DIPNET_DAYS = 0; END;
     IF KASILOF_GILLNET_HARVEST = . THEN DO; KASILOF_GILLNET_HARVEST = 0; KASILOF_GILLNET_DAYS = 0; END;
     IF FISH_CREEK_HARVEST = . THEN DO; FISH_CREEK_HARVEST = 0; FISH_CREEK_DAYS = 0; END;
     IF UNKNOWN_HARVEST = . THEN DO; UNKNOWN_HARVEST = 0; UNKNOWN_DAYS = 0; END;
     IF FISHERIES = . THEN FISHERIES = 0;
     TOTAL_DAYS = KENAI_DAYS + KASILOF_DIPNET_DAYS + KASILOF_GILLNET_DAYS + FISH_CREEK_DAYS + UNKNOWN_DAYS;
     HOUSEHOLD_SIZE = ((ALLOWED - 25) / 10) + 1;
     YEAR = 2010;
     DROP FISHERY1 FISHERY2 FISHERY3;

DATA ALL2; 
     RETAIN YEAR PERMIT ALLOWED RED KING COHO PINK CHUM SALMON FISHERIES KENAI_HARVEST KENAI_DAYS KASILOF_DIPNET_HARVEST 
            KASILOF_DIPNET_DAYS KASILOF_GILLNET_HARVEST KASILOF_GILLNET_DAYS FISH_CREEK_HARVEST FISH_CREEK_DAYS UNKNOWN_HARVEST UNKNOWN_DAYS 
            TOTAL_DAYS HOUSEHOLD_SIZE;
     SET ALL;
PROC PRINT DATA = ALL2 (OBS = 50);
RUN;

PROC MEANS SUM;
     VAR KENAI_HARVEST KASILOF_DIPNET_HARVEST KASILOF_GILLNET_HARVEST FISH_CREEK_HARVEST UNKNOWN_HARVEST;
RUN;

DATA SASDATA.EXTRA2010; SET ALL2;
RUN;


********************************************************************************************************************************************;
*         NEED TO COPY/MOVE SASDATA.EXTRA20XX FROM THE YEAR FOLDER TO THE REPORT FOLDER BEFORE RUNNING THE REST OF THIS PROGRAM            *;
********************************************************************************************************************************************;

/*
LIBNAME SASDATA BASE "O:\DSF\RTS\Pat\Permits\Salmon\REPORT 2010-2012";

DATA EXTRA_2010_2011_2012; SET SASDATA.EXTRA2010 SASDATA.EXTRA2011 SASDATA.EXTRA2012;
     IF FISH_CREEK_HARVEST = . THEN DO; FISH_CREEK_HARVEST = 0; FISH_CREEK_DAYS = 0; END;
     PERCENT_ALLOWED = ROUND((SALMON / ALLOWED) * 100,1);
     EXTRA = 1;
     DROP TRIPS;
PROC SORT; BY YEAR PERMIT;
RUN;
proc contents;
run;
PROC PRINT DATA = EXTRA_2010_2011_2012 (OBS = 1000);
RUN;

LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\SALMON\2010";
DATA PERSONAL2010; SET SASDATA.PERSONAL;
     LENGTH C $19;
     YEAR = 2010;
     KEEP YEAR PERMIT CITY C;

DATA PERSONAL2010; SET PERSONAL2010;
     C = CITY;
     DROP CITY;
RUN;

LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\SALMON\2011";
DATA PERSONAL2011; SET SASDATA.PERSONAL;
     LENGTH C $19;
     YEAR = 2011;
     KEEP YEAR PERMIT CITY C;
DATA PERSONAL2011; SET PERSONAL2011;
     C = CITY;
     DROP CITY;
RUN;

LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\SALMON\2012";
DATA PERSONAL2012; SET SASDATA.PERSONAL;
     LENGTH C $19;
     YEAR = 2012;
     KEEP YEAR PERMIT CITY C;
DATA PERSONAL2012; SET PERSONAL2012;
     C = CITY;
     DROP CITY;
RUN;

DATA PERSONAL; SET PERSONAL2010 PERSONAL2011 PERSONAL2012;
     RENAME C = CITY;
     PERSONAL = 1;
PROC SORT; BY YEAR PERMIT;
RUN;



DATA EXTRA_2010_2011_2012; MERGE EXTRA_2010_2011_2012 PERSONAL; BY YEAR PERMIT;
     IF EXTRA = 1;
PROC SORT; BY CITY;
RUN; 
PROC PRINT DATA = EXTRA_2010_2011_2012 (OBS = 1000);
RUN;










LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\SALMON";
DATA CITY; SET SASDATA.CITIES;
PROC SORT; BY CITY;

DATA EXTRA_2010_2011_2012; MERGE CITY EXTRA_2010_2011_2012; BY CITY;
     IF EXTRA = 1;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;
     DROP EXTRA;

DATA EXTRA_2010_2011_2012; SET EXTRA_2010_2011_2012;
     IF CITY = ' ' THEN REGION = 4;
     DROP NEW_NAME TRIPS EXTRA PERSONAL;
RUN;


PROC SORT DATA = EXTRA_2010_2011_2012; BY YEAR PERMIT;
PROC PRINT DATA = EXTRA_2010_2011_2012 (OBS = 100);
RUN;

PROC CONTENTS DATA = EXTRA_2010_2011_2012;
RUN;

DATA EXTRA_2010_2011_2012_B; SET EXTRA_2010_2011_2012;
DATA EXTRA_2010_2011_2012; 
     RETAIN YEAR PERMIT CITY REGION AREA ALLOWED RED KING COHO PINK CHUM SALMON 
            PERCENT_ALLOWED FISHERIES KENAI_HARVEST KENAI_DAYS KASILOF_DIPNET_HARVEST KASILOF_DIPNET_DAYS 
            KASILOF_GILLNET_HARVEST KASILOF_GILLNET_DAYS FISH_CREEK_HARVEST FISH_CREEK_DAYS 
            UNKNOWN_HARVEST UNKNOWN_DAYS TOTAL_DAYS HOUSEHOLD_SIZE;
     SET EXTRA_2010_2011_2012_B;
PROC PRINT DATA = EXTRA_2010_2011_2012 (OBS = 100);
RUN;


DATA EXPORT1; SET EXTRA_2010_2011_2012;
     IF FISHERIES GE 0;
PROC EXPORT DATA= EXPORT1 
     OUTFILE= "O:\DSF\RTS\PAT\Permits\Salmon\REPORT 2010-2012\MORE EXTRA ESTIMATES.xls" 
     DBMS=EXCEL REPLACE;
     SHEET="DATA FISHERIES GE 0"; 
RUN;

DATA EXPORT2; SET EXTRA_2010_2011_2012;
     IF FISHERIES EQ 1;
PROC EXPORT DATA= EXPORT2 
     OUTFILE= "O:\DSF\RTS\PAT\Permits\Salmon\REPORT 2010-2012\MORE EXTRA ESTIMATES.xls" 
     DBMS=EXCEL REPLACE;
     SHEET="DATA FISHERIES EQ 1"; 
RUN;

DATA EXPORT3; SET EXTRA_2010_2011_2012;
     IF FISHERIES GE 1;
PROC EXPORT DATA= EXPORT3 
     OUTFILE= "O:\DSF\RTS\PAT\Permits\Salmon\REPORT 2010-2012\MORE EXTRA ESTIMATES.xls" 
     DBMS=EXCEL REPLACE;
     SHEET="DATA FISHERIES GE 1"; 
RUN;

*/

/*
PROC DATASETS KILL;
RUN;
*/



/*
PROC IMPORT OUT= WORK.CHECK DATAFILE= "O:\DSF\RTS\Pat\Permits\Salmon\REPORT 2007-2009\MORE EXTRA ESTIMATES2.xlsx" DBMS=EXCEL REPLACE;
     RANGE="'DATA FISHERIES GE 1$'"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;

PROC PRINT DATA = CHECK (OBS = 50);
RUN;


PROC SORT; BY YEAR;
PROC MEANS SUM; BY YEAR;
     VAR SALMON;
RUN;
*/
