OPTIONS PAGESIZE = 60;
OPTIONS LINESIZE = 106;
%LET PROJECT = SALMON;
%LET DATA = CISLHV05C;
%LET YEAR = 2005;
%LET SP = SALMON;
%LET SPECIES_COMMA = RED,KING,COHO,PINK,CHUM,FLOUNDER; *QQQ;
%LET SPECIES_LIST = RED KING COHO PINK CHUM FLOUNDER; *QQQ;
%LET PROGRAM = HARVEST;
%LET GILLNET_START = '15JUN05'D; 
%LET GILLNET_STOP = '24JUN05'D; 


OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
LIBNAME SASDATA BASE "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
*ODS RTF FILE = "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR\&PROGRAM..RTF";
RUN;


TITLE1 "&PROJECT - &YEAR";


**************************************************************************;
*                              HARVEST DATA                              *;
**************************************************************************;
/*
PROC CONTENTS DATA = SASDATA.&DATA;
RUN;
*/
DATA HARVEST; SET SASDATA.&DATA (DROP =  YEAR KEYDATE HVRECID MAILING KEYID EDITED);
     IF NOCATCH = 1 THEN CATCH = 'N'; IF NOCATCH NE 1 THEN CATCH = 'Y';
     IF NOHRVRPT = 1 THEN HRVRPT = 'N'; IF NOHRVRPT NE 1 THEN HRVRPT = 'Y';
     IF FISHERY = '' THEN FISHERY = 'UNKNOWN';
/*
     IF FISHERY = 'KENAI' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KENAI' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 6 AND DAY LT 15 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 8 AND DAY GT 7 THEN HARVDATE = '01JAN90'D;
*/
     IF HARVDATE EQ '01JAN01'D THEN HARVDATE = .;
     MONTH = MONTH(HARVDATE); DAY = DAY(HARVDATE); YEAR = YEAR(HARVDATE); 
     SASDATE = MDY(MONTH,DAY,YEAR); JDATE = JULDATE(SASDATE)-((&YEAR - 2000)*1000);
     IF JDATE GT 365 THEN JDATE = .;
     WEEK = INT(CEIL((JDATE - 2)/7));

     RENAME PERMITNO = PERMIT; 
     DROP NOCATCH NOHRVRPT SASDATE JDATE COMMENTS CATCH HRVRPT YEAR;
RUN;

DATA HARVEST; SET HARVEST;
     IF FISHERY = 'UNKNOWN' AND MONTH = 6 AND DAY GE 15 THEN FISHERY = 'KASILOF';
     IF FISHERY = 'UNKNOWN' AND MONTH = 7 AND DAY LE 9 THEN FISHERY = 'KASILOF';
     IF FISHERY = 'UNKNOWN' AND MONTH = 8 AND DAY GE 1 AND DAY LE 7 THEN FISHERY = 'KASILOF';

     IF FISHERY = 'FISH CREEK' THEN FISHERY = 'KENAI';
     IF PERMIT = 21519 AND MONTH = 6 AND DAY = 13 THEN FISHERY = 'KASILOF';
     IF PERMIT = 24549 AND MONTH = 6 AND DAY = 15 THEN FISHERY = 'KASILOF';

   *  DROP MONTH DAY;
RUN;

   

PROC SORT DATA = HARVEST; BY PERMIT;     
PROC PRINT DATA = HARVEST (OBS = 40);
     TITLE2 'HARVEST FILE';
     TITLE3 ;
RUN;

PROC FREQ;
     TABLES FISHERY;

PROC SORT; BY PERMIT HARVDATE FISHERY;

DATA UNKNOWN; SET HARVEST;
     IF FISHERY = 'UNKNOWN';
     UNKNOWN = 'Y';
PROC SORT DATA = UNKNOWN; BY PERMIT HARVDATE;
DATA UNKNOWN; SET UNKNOWN; BY PERMIT;
     IF FIRST.PERMIT;
PROC MEANS N;
     VAR PERMIT;
     TITLE2 'THE NUMBER OF PERMITS';
     TITLE3 'WITH AT LEAST 1 UNKNOWN FISHERY';

DATA UNKNOWN; SET UNKNOWN; 
     KEEP PERMIT UNKNOWN;

DATA UNKNOWN2; MERGE UNKNOWN HARVEST; BY PERMIT;
     IF UNKNOWN = 'Y';

PROC PRINT DATA = UNKNOWN2 (OBS = 300);
     TITLE2 'HARVEST RECORDS FROM PERMITS';
     TITLE3 'WITH AT LEAST 1 UNKNOWN FISHERY';
     TITLE4 'OBS = 400';
RUN;

PROC FREQ; BY PERMIT;
     TABLES FISHERY / NOPRINT OUT = UNKNOWN3;

DATA UNKNOWN4; SET UNKNOWN3;
     IF FISHERY = 'UNKNOWN' AND PERCENT = 100;
     ALWAYS_UNKNOWN = 'Y';
PROC MEANS N;
     VAR PERMIT;
     TITLE2 'THE NUMBER OF PERMITS';
     TITLE3 'WHERE FISHERY IS ALWAYS UNKNOWN';
RUN;

DATA UNKNOWN5; MERGE UNKNOWN4 HARVEST; BY PERMIT;
     IF ALWAYS_UNKNOWN = 'Y';
PROC MEANS N;
     VAR PERMIT;
     TITLE2 'THE NUMBER OF HARVEST RECORDS FROM PERMITS';
     TITLE3 'WHERE FISHERY IS ALWAYS UNKNOWN';
RUN;

PROC PRINT DATA = UNKNOWN3;
     WHERE PERCENT LT 100;
     TITLE2 'HARVEST RECORDS FROM PERMITS';
     TITLE3 'WHERE FISHERY IS NOT ALWAYS UNKNOWN';
RUN;
PROC FREQ DATA = UNKNOWN3;
     WHERE PERCENT LT 100;;
     TABLES PERMIT / NOPRINT OUT = NOT_ALL_UNKNOWN;

DATA UNKNOWN6; SET NOT_ALL_UNKNOWN;
     NOT_ALL_UNKNOWN = 'Y';
     DROP COUNT PERCENT;
 
DATA UNKNOWN7; MERGE UNKNOWN6 HARVEST; BY PERMIT;
     IF NOT_ALL_UNKNOWN = 'Y';
PROC SORT; BY PERMIT HARVDATE FISHERY;
PROC PRINT;
     TITLE2 'HARVEST RECORDS FROM PERMITS';
     TITLE3 'WHERE FISHERY IS NOT ALWAYS UNKNOWN';
RUN;


PROC FREQ;
     TABLES PERMIT / NOPRINT OUT = ALLUNKNOWN;
PROC MEANS SUM;
     VAR COUNT;
     TITLE2 'THESE PERMITS WERE ALWAYS UNKNOWN FISHERY';
RUN;



DATA HARVEST; SET HARVEST;
     IF MONTH = 7 AND DAY = 10 THEN WEEK = 28;

PROC FREQ;
     TABLES FISHERY * WEEK;
RUN;

PROC FREQ;
     WHERE WEEK = 28 OR WEEK = 29 OR WEEK = 30;
     TABLES FISHERY * WEEK / OUT=UNKNOWNB;
RUN;
PROC PRINT DATA = UNKNOWNB;
RUN;




