OPTIONS PAGENO=1;
%LET PROJECT = SALMON;
%LET YEAR = 2001;



LIBNAME SASDATA BASE "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR" SHORTFILEEXT;
RUN;
DATA ONE; SET SASDATA.CISLPM01C;
DATA ONEZ; SET SASDATA.CISLPM01Z;
DATA TWO; SET SASDATA.CISLHV01C;
RUN;

DATA ONE; SET ONE ONEZ;


LIBNAME SASDATA BASE "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
RUN;

DATA SASDATA.CISLPM01C; SET ONE;
DATA SASDATA.CISLHV01C; SET TWO;


RUN;
