*Get Permit files from past years with adresess;
libname UCIPERM 'H:\My Documents\Personal Use\Imported files\From Hazzy';
LIBNAME SASDATA 'H:\My Documents\Personal Use\Imported files\From Pat Hansen';
libname Illegals 'H:\My Documents\Personal Use\Imported files\From Kirk Brogdon';
LIBNAME SASDATA2 'H:\My Documents\Personal Use\Imported files\From Pat Hansen\03 stuff';

* 1996;
data per96; set uciperm.harv96;
	year = 1996;
	keep year licensen firstnam lastname address city state zipcode dateiss;
	rename licensen=idnum firstnam=firstname; 
run;
* 1997;
data per97; set uciperm.perm97;
	year = 1997; idnum=input(cisalprm, $char6.); idnum=cisalprm;
	keep year idnum firstnam lastname address city state zipcode dateiss;
	rename firstnam=firstname; 
run;
* 1998;
data per98; set illegals.NRPU98; 
	year = 1998; idnum=input(cisalprmno, $char6.); idnum=cisalprmno;
	keep year idnum firstnam lastname address city state zipcode dateiss;
	rename firstnam=firstname; 
run;
* 1999;
data per99; set uciperm.permit99;
	year = 1999; idnum=input(cisalprm, $char6.); idnum=cisalprm;
	keep year idnum firstnam lastname address city state zipcode dateiss;
	rename firstnam=firstname; 
run;
* 2000;
data per00; set illegals.NRPU2000; 
	year = 2000; idnum=input(cisalprmno, $char6.); idnum=cisalprmno;
	keep year idnum firstnam lastname address city state zipcode dateiss;
	rename firstnam=firstname; 
run;
* 2001;
data per01z; set sasdata.cislpm01z; run;
data per01c; set sasdata.cislpm01c; run;
data per01; set per01z per01c; 
	year = 2001; idnum=input(permitno, $char6.); idnum=permitno;
	keep year idnum first_name last_name address city state zipcode dateiss;
	rename first_name=firstname last_name=lastname; 
run;
* 2002;
data per02; set sasdata.cislpm02c; 
	year = 2002; idnum=input(permitno, $char6.); idnum=permitno;
	keep year idnum first_name last_name address city state zipcode dateiss;
	rename first_name=firstname last_name=lastname;
run;
* 2003;
data per03; set sasdata2.cislpm02c; 
	year = 2003; idnum=input(permitno, $char6.); idnum=permitno;
	keep year idnum first_name last_name address city state zipcode dateiss;
	rename first_name=firstname last_name=lastname;
run;

*append permit files;
data personal; set per96 per97 per98 per99 per00 per01 per02; 
	if state eq 'AK' then delete; 
	if state eq ' ' then delete;
	if state eq '99' then delete;
	if year(dateiss) ne year then dateiss=.;
	if month(dateiss)=1 then dateiss=.;
	run;
proc sort data=personal; by year city; run;
proc print data=personal noobs; 
	var year idnum firstname lastname address city state zipcode dateiss;
	run;