%LET YEAR = 2015;


OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
LIBNAME SASDATA BASE "S:\RTS\common\Pat\Permits\Salmon\&YEAR";
RUN;

DATA PERSONAL; SET SASDATA.PERSONAL (KEEP = PERMIT CITY);
PROC SORT; BY PERMIT; RUN;

DATA ISSUED; SET SASDATA.ISSUED (KEEP = PERMIT STATUS);
PROC SORT; BY PERMIT; RUN;

DATA SALMON_HARVEST; SET SASDATA.SALMON_HARVEST (KEEP = PERMIT FISHERY RED MONTH DAY);
     RENAME FISHERY = LOCATION;

DATA SALMON_HARVEST; SET SALMON_HARVEST;
     IF LOCATION EQ 'KASILOF' AND MONTH = 6 AND DAY GE 15 AND DAY LE 24 THEN FISHERY = 'KASILOF GILLNET';  *GILLNET;
     IF LOCATION EQ 'KASILOF' AND FISHERY = '' THEN FISHERY = 'KASILOF DIPNET';  *DIPNET;
	 IF LOCATION NE 'KASILOF' THEN FISHERY = LOCATION;
	 DROP LOCATION MONTH DAY;
RUN;

PROC SORT; BY PERMIT FISHERY;
PROC MEANS SUM NOPRINT; BY PERMIT FISHERY;
     VAR RED;
     OUTPUT OUT = HARVEST SUM = SOCKEYE;

DATA HARVEST; SET HARVEST (DROP = _TYPE_ _FREQ_);

DATA MARIA&YEAR; MERGE PERSONAL ISSUED HARVEST; BY PERMIT;
     IF STATUS = 'DID NOT FISH' THEN SOCKEYE = 0;
	 IF CITY = 'NINILCHIK';
	 YEAR = &YEAR;
PROC PRINT DATA = MARIA&YEAR (OBS = 50);
     TITLE1 "DATA FROM &YEAR";
RUN;

DATA MARIA; SET MARIA2011-MARIA2015;
RUN;


PROC FREQ DATA = MARIA;
     TABLES STATUS / NOPRINT OUT = STATUS_SUMMARY;
PROC PRINT DATA = STATUS_SUMMARY;
     TITLE1 'STATUS SUMMARY';
RUN;

DATA MARIA2; SET MARIA;
	 IF FISHERY = 'KASILOF GILLNET' OR FISHERY = 'KASILOF DIPNET' OR FISHERY = 'KENAI';

PROC SORT; BY FISHERY;
PROC MEANS SUM NOPRINT; BY FISHERY;
     VAR SOCKEYE;
	 OUTPUT OUT = HARVEST SUM = SOCKEYE;
PROC PRINT DATA = HARVEST;
     TITLE1 'REPORTED HARVEST';
	 TITLE2 'NINILCHIK RESIDENTS ONLY';
	 TITLE3 'KASILOF GILLNET, KASILOF DIPNET AND KENAI DIPNET ONLY'; 
	 TITLE4 '2011 - 2015 ONLY';
RUN;



