%LET PROJECT = SALMON;
%LET YEAR = 2013;
%LET GILLNET_START = '15JUN13'D; 
%LET GILLNET_STOP = '24JUN13'D; 

OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
LIBNAME SASDATA BASE "O:\DSF\RTS\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
RUN;


PROC IMPORT OUT= WORK.PERMITS DATAFILE= "O:\DSF\RTS\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" DBMS=EXCEL REPLACE;
     RANGE="PERMIT_RECORDS$"; 
     GETNAMES=YES; MIXED=NO; SCANTEXT=YES; USEDATE=YES; SCANTIME=YES;
RUN;

DATA PERMITS; SET PERMITS (KEEP = PERMIT MAILING STATUS);
     IF MAILING = 9 THEN DELETE;
     IF STATUS = 'HARVEST REPORTED';
PROC SORT DATA = PERMITS; BY PERMIT;
RUN;



PROC IMPORT OUT= WORK.HARVEST DATAFILE= "O:\DSF\RTS\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" DBMS=EXCEL REPLACE;
     RANGE="HARVEST_RECORDS$"; 
     GETNAMES=YES; MIXED=NO; SCANTEXT=YES; USEDATE=YES; SCANTIME=YES;
RUN;

PROC SORT DATA = HARVEST; BY PERMIT HARVDATE;

DATA KASILOF_KINGS; MERGE PERMITS HARVEST; BY PERMIT;
     IF FISHERY = 'KASILOF' AND MAILING = 0; 
	 DROP FLOUNDER;
RUN;

PROC MEANS DATA = KASILOF_KINGS SUM NOPRINT;
     VAR KING;
	 OUTPUT OUT = VOLUNTARY_RETURNS SUM = JUNK N = ANGLERS;

PROC MEANS DATA = KASILOF_KINGS SUM NOPRINT;
     WHERE HARVDATE GE &GILLNET_START AND HARVDATE LE &GILLNET_STOP;
     VAR KING;
	 OUTPUT OUT = KING_HARVEST_VOLUNTARY SUM = KINGS_VOLUNTARY;
DATA KING_HARVEST_VOLUNTARY; MERGE KING_HARVEST_VOLUNTARY VOLUNTARY_RETURNS;
     YEAR = &YEAR;
     DROP _TYPE_ _FREQ_ JUNK;
PROC PRINT DATA = KING_HARVEST_VOLUNTARY;
RUN;

DATA KK&YEAR; SET KING_HARVEST_VOLUNTARY;
RUN;





/*
DATA KK; SET KK2004-KK2013;
PROC PRINT;
RUN;
*/





/*
PROC FREQ DATA = KASILOF_KINGS;
     TABLES KING / OUT=FREQ;
RUN;

PROC PRINT DATA = FREQ;
RUN;

DATA EXPANDED; SET SASDATA.FINAL_ESTIMATES (RENAME=(VARIABLE=SPECIES BHH3=EXPANDED_KASILOF_KINGS SE3 = SE));
     IF SPECIES = 'king';
	 YEAR = &YEAR;
	 KEEP SPECIES EXPANDED_KASILOF_KINGS SE YEAR;
	

PROC PRINT;
RUN;

PROC CONTENTS;
RUN;
*/

