%LET PROJECT = SALMON;
%LET YEAR = 2014;
%LET GILLNET_START = '15JUN14'D; 
%LET GILLNET_STOP = '24JUN14'D; 

OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
LIBNAME SASDATA BASE "O:\DSF\RTS\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
RUN;


PROC IMPORT OUT= WORK.PERMITS DATAFILE= "O:\DSF\RTS\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" DBMS=EXCEL REPLACE;
     RANGE="PERMIT_RECORDS$"; 
     GETNAMES=YES; MIXED=NO; SCANTEXT=YES; USEDATE=YES; SCANTIME=YES;
RUN;

DATA PERMITS; SET PERMITS (KEEP = PERMIT MAILING STATUS);
     IF MAILING = 9 THEN DELETE;
     IF STATUS = 'HARVEST REPORTED';
PROC SORT DATA = PERMITS; BY PERMIT;

PROC MEANS DATA = PERMITS SUM NOPRINT;
     WHERE MAILING = 0;
     VAR MAILING;
     OUTPUT OUT = VOLUNTARY_RETURNS SUM = JUNK N = ANGLERS;
PROC PRINT DATA = VOLUNTARY_RETURNS;
RUN;



PROC IMPORT OUT= WORK.HARVEST DATAFILE= "O:\DSF\RTS\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" DBMS=EXCEL REPLACE;
     RANGE="HARVEST_RECORDS$"; 
     GETNAMES=YES; MIXED=NO; SCANTEXT=YES; USEDATE=YES; SCANTIME=YES;
RUN;

DATA HARVEST; SET HARVEST;

PROC SORT DATA = HARVEST; BY PERMIT HARVDATE;

DATA SALMON; MERGE PERMITS HARVEST (RENAME = (FISHERY = LOCATION)); BY PERMIT;
     IF MAILING = 0;
     IF LOCATION = 'FISHCREEK' OR LOCATION = 'UNKNOWN' THEN DELETE;
     IF LOCATION = 'KENAI' THEN GEAR = 'DIPNET ';
     IF LOCATION = 'KASILOF' AND HARVDATE GE &GILLNET_START AND HARVDATE LE &GILLNET_STOP THEN GEAR = 'GILLNET';
     IF LOCATION = 'KASILOF' AND (HARVDATE LT &GILLNET_START OR HARVDATE GT &GILLNET_STOP) THEN GEAR = 'DIPNET';
     IF GEAR NE '' THEN FISHERY = COMPRESS(LOCATION||'-'||GEAR);
     IF GEAR EQ '' THEN FISHERY = COMPRESS(LOCATION);
     DROP FLOUNDER STATUS LOCATION GEAR HARVDATE MAILING COHO PINK CHUM;

PROC FREQ;
TABLES FISHERY;
RUN;

PROC SORT DATA = SALMON; BY FISHERY;
PROC MEANS DATA = SALMON SUM NOPRINT; BY FISHERY;
     VAR RED KING;
     OUTPUT OUT = HARVEST_VOLUNTARY SUM = V_RED V_KING;
DATA HARVEST_VOLUNTARY; SET HARVEST_VOLUNTARY;
     YEAR = &YEAR;
     DROP _TYPE_ _FREQ_;
PROC PRINT DATA = HARVEST_VOLUNTARY;
RUN;

DATA EXPANDED; SET SASDATA.FINAL_ESTIMATES (KEEP = VARIABLE BHH1 BHH2 BHH3);
     IF VARIABLE = 'king' OR VARIABLE = 'red';
PROC PRINT;
RUN;

PROC TRANSPOSE DATA = EXPANDED OUT = EXPANDED_T;
DATA EXPANDED_T; SET EXPANDED_T (RENAME = (COL1 = NV_KING COL2 = NV_RED));
     IF _NAME_ = 'BHH1' THEN FISHERY = 'KENAI-DIPNET   ';
     IF _NAME_ = 'BHH2' THEN FISHERY = 'KASILOF-DIPNET';
     IF _NAME_ = 'BHH3' THEN FISHERY = 'KASILOF-GILLNET';
     DROP _NAME_;
PROC SORT; BY FISHERY;
PROC PRINT;
RUN;


DATA HARVEST&YEAR; MERGE HARVEST_VOLUNTARY EXPANDED_T; BY FISHERY;
     IF FISHERY = 'FISHCREEK' THEN DELETE;
PROC PRINT;
RUN;
