PROC DATASETS KILL;
RUN;


%LET PROJECT = SALMON;
%LET YEAR = 2017;
%LET PROGRAM = PERMIT;


OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
LIBNAME SASDATA  "O:\DSF\RTS\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
*LIBNAME SASDATA  "O:\DSF\RTS\COMMON\Pat\Permits\Salmon\Subsistence\&YEAR";
RUN;

TITLE1 "&PROJECT - &YEAR";

**************************************************************************;
*                              PERMIT DATA                               *;
**************************************************************************;

PROC SORT DATA = SASDATA.ISSUED; BY PERMIT;
PROC SORT DATA = SASDATA.PERSONAL; BY PERMIT;

DATA PERMITS; MERGE SASDATA.ISSUED SASDATA.PERSONAL; BY PERMIT;
     IF STATUS = 'HARVEST REPORTED' THEN FISHED = 'Y';  ELSE FISHED = 'N';
     IF CITY = 'XXX' THEN COMMUNITY = '1234567890123456789';
     COMMUNITY = CITY;
     IF CITY = 'ACHORAGE' THEN COMMUNITY = 'ANCHORAGE';
     IF CITY = 'AKKOKHANOK' THEN COMMUNITY = 'KOKHANOK';
     IF CITY = 'ALAMOGORDO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'ALBUQUERQUE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'ANCHOR PT' THEN COMMUNITY = 'ANCHOR POINT';
     IF CITY = 'ANCHOR RIVER' THEN COMMUNITY = 'ANCHOR POINT';
     IF CITY = 'ANCHORAGEG' THEN COMMUNITY = 'ANCHORAGE';
     IF CITY = 'ANCHORGAGE' THEN COMMUNITY = 'ANCHORAGE';
     IF CITY = 'ANCHORGE' THEN COMMUNITY = 'ANCHORAGE';
     IF CITY = 'ANCHROAGE' THEN COMMUNITY = 'ANCHORAGE';
     IF CITY = 'ANCORAGE' THEN COMMUNITY = 'ANCHORAGE';
     IF CITY = 'ANHCORAGE' THEN COMMUNITY = 'ANCHORAGE';
     IF CITY = 'APO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'AUKE BAY' THEN COMMUNITY = 'JUNEAU';
     IF CITY = 'BARLEY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'BARONOFF' THEN COMMUNITY = 'SITKA';
     IF CITY = 'BARRIGADA' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'BETTLES FIELD' THEN COMMUNITY = 'BETTLES';
     IF CITY = 'BIGFORK' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'BIRD CREEK' THEN COMMUNITY = 'ANCHORAGE';
     IF CITY = 'BOISE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'BOLLING AFB' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'BOX ELDER' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'BURKE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'CANYON LAKE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'CAPTAIN COOK' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'CHEYENNE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'CHUGAIK' THEN COMMUNITY = 'CHUGIAK';
     IF CITY = 'CLAYTON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'CLEAR AFS' THEN COMMUNITY = 'CLEAR';
     IF CITY = 'CLOUDCROFT' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'CLOVIS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'COLORADO SPRINGS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'CORTEZ' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'CORVALLIS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'CRESTVIEW' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'DAYTON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'DEADHORSE' THEN COMMUNITY = 'PRUDHOE BAY';
     IF CITY = 'DEL RIO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'DELTA' THEN COMMUNITY = 'DELTA JUNCTION';
     IF CITY = 'DELTA JCT' THEN COMMUNITY = 'DELTA JUNCTION';
     IF CITY = 'DENALI NATIONAL PARK' THEN COMMUNITY = 'DENALI PARK';
     IF CITY = 'DERBY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'DOUGLAS' THEN COMMUNITY = 'JUNEAU';
     IF CITY = 'DUTCH HARBOR' THEN COMMUNITY = 'UNALASKA';
     IF CITY = 'DYESS AFB' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'EAFB' THEN COMMUNITY = 'JBER';
     IF CITY = 'EAGLE RVER' THEN COMMUNITY = 'EAGLE RIVER';
     IF CITY = 'EAGLER RIVER' THEN COMMUNITY = 'EAGLE RIVER';
     IF CITY = 'EDISON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'EDMOND' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'EDMONDS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'EGLIN AFB' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'ELEMENDORF AFB' THEN COMMUNITY = 'JBER';
     IF CITY = 'ELK RIVER' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'ELMENDORF' THEN COMMUNITY = 'JBER';
     IF CITY = 'ELMENDORF AFB' THEN COMMUNITY = 'JBER';
     IF CITY = 'ERIE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'EVERETT' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'FAIBANKS' THEN COMMUNITY = 'FAIRBANKS ';
     IF CITY = 'FAIRMONT' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'FALLS CHURCH' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'FLORENCE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'FORT CARSON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'FORT RICHARDSON' THEN COMMUNITY = 'JBER';
     IF CITY = 'FORT SILL' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'FORT WAINWRIGH' THEN COMMUNITY = 'FORT WAINWRIGHT';
     IF CITY = 'FREDERICKSBURG' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'FT GREELY' THEN COMMUNITY = 'FORT GREELY';
     IF CITY = 'FT RICHARDSON' THEN COMMUNITY = 'JBER';
     IF CITY = 'FT RICHARDSON AFB' THEN COMMUNITY = 'JBER';
     IF CITY = 'FT WAINWRIGHT' THEN COMMUNITY = 'FORT WAINWRIGHT';
     IF CITY = 'FT. RICHARDSON' THEN COMMUNITY = 'JBER';
     IF CITY = 'FUNNY RIVER' THEN COMMUNITY = 'STERLING';
     IF CITY = 'GAINESVILLE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'GIG HARBOR' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'GILBERT' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'GOLDSBORO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'GOODNEWS BAY' THEN COMMUNITY = 'GOODNEWS';
     IF CITY = 'GRAND RAPIDS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'GREAT FALLS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'GYPSUM' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HANSCOM AFB' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HAWTHORNE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HIBOR HEIGHTS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HIGHLANDS RANCH' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HILL AFB' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HOEMR' THEN COMMUNITY = 'HOMER';
     IF CITY = 'HOLLOMAN AFB' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HOM,ER' THEN COMMUNITY = 'HOMER';
     IF CITY = 'HONOLULU' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HOPKINSVILLE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HORNELL' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'HUSTON' THEN COMMUNITY = 'HOUSTON';
     IF CITY = 'IMPERIAL' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'INDIAN' THEN COMMUNITY = 'ANCHORAGE';
     IF CITY = 'INVERNESS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'KACHEMACK CITY' THEN COMMUNITY = 'HOMER';
     IF CITY = 'KANEOHE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'KASLIOF' THEN COMMUNITY = 'KASILOF';
     IF CITY = 'KENT' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'KINGMAN' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'KLAMATH FALLS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'KOKHANEK' THEN COMMUNITY = 'KOKHANOK';
     IF CITY = 'LA GRANGE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'LACEY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'LAPORTE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'LAS VEGAS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'LEBANON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'LITTLE ROCK' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'LIVINGSTON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MACON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MANHATTAN' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MC GRATH' THEN COMMUNITY = 'MCGRATH';
     IF CITY = 'MC MARTON AVE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MEADOW LAKE' THEN COMMUNITY = 'WASILLA';
     IF CITY = 'MEADOW LAKES' THEN COMMUNITY = 'WASILLA';
     IF CITY = 'MELBOURNE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'METLAKATLA' THEN COMMUNITY = 'METLAKATKA';
     IF CITY = 'MILILANI' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MILLBROOK' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MILLERSBURG' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MINOT AFB' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MISSION' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MONROE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MONTGOMERY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MONUMENT' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MOUNT VERNON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MOUNTAIN HOME' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MOUNTAIN HOME A F B' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'MURRUTA' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'NAPASKIAK' THEN COMMUNITY = 'NAPAKIAK';
     IF CITY = 'NISKISKI' THEN COMMUNITY = 'NIKISKI';
     IF CITY = 'NORTH LAS VEGAS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'NORTH POL' THEN COMMUNITY = 'NORTH POLE';
     IF CITY = 'NUSTON' THEN COMMUNITY = 'HOUSTON';
     IF CITY = 'O FALLON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'OLIKTOK' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'OLYMPIA' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'ORLANDO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'PALME' THEN COMMUNITY = 'PALMER';
     IF CITY = 'PETALUMA' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'PHENIX CITY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'PINETOP' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'PO BOX 222633' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'PORT CHARLOTTE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'PORTALES' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'PORTLAND' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'PRATTVILLE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'PROVO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'RAPID CITY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'RENO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'RINGWOOD' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'ROCHESTER' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'RUSHVILLE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SAINT PAUL' THEN COMMUNITY = 'SAINT PAUL ISLAND';
     IF CITY = 'SALEM' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SALT ALKE CITY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SALT LAKE CITY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SAN ANTONIO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SAN DIEGO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SANFORD' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SAVANNAH' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SCAMMON' THEN COMMUNITY = 'SCAMMON BAY';
     IF CITY = 'SCOTTSDALE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SEATTLE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SHAW A F B' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SIERRA VISTA' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SPANAWAY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SPARKS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SPOKANE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SPRINGFIELD' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'SPRUCE CREST DR #B' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'ST LOUIS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'ST PAUL ISLAND' THEN COMMUNITY = 'SAINT PAUL ISLAND';
     IF CITY = 'STAFFORD' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'STGERLING' THEN COMMUNITY = 'STERLING';
     IF CITY = 'SUISUN CITY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'TIORC' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'TRAVIS AFB' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'TROY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'TUCSON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'TULLY' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'UNION GAP' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'VACAVILLE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'VALRICO' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'WALDORF' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'WARD COVE' THEN COMMUNITY = 'KETCHIKAN';
     IF CITY = 'WARNER ROBINS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'WARRENSBURG' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'WASHINGTON' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'WAYNESVILLE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'WICHITA FALLS' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'WILSON ST SPC 18' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'WOODBRIDGE' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'WOODBURN' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = 'YANGE ST' THEN COMMUNITY = 'UNKNOWN';
     IF CITY = '' THEN COMMUNITY = 'UNKNOWN';
     KEEP PERMIT STATUS VENDORCOPY RESPONDED FISHED COMMUNITY;

PROC PRINT DATA = PERMITS (OBS=10);
     TITLE2 'PERMIT DATABASE';
     TITLE3 'FIRST 10 RECORDS';
RUN; 

PROC FREQ DATA = PERMITS;
     TABLES STATUS VENDORCOPY RESPONDED FISHED STATUS*RESPONDED;
RUN;


PROC MEANS NOPRINT DATA = PERMITS;
     VAR PERMIT;
     OUTPUT OUT = KNOWN_ISSUED N = KNOWN_ISSUED MAX = MAX;

DATA ORPHANS; MERGE KNOWN_ISSUED SASDATA.TOTAL_ISSUED;
     NO_RESP_ORPHANS = NHAT - KNOWN_ISSUED;
     DROP _TYPE_ _FREQ_ VAR_NHAT;
PROC PRINT;
RUN;


DATA NO_RESP_ORPHANS; SET ORPHANS;
     DO PERMIT = 1 TO NO_RESP_ORPHANS;
        STATUS = 'NON RESPONDENT';
        VENDORCOPY = 'N';
        COMMUNITY = 'UNKNOWN';
        RESPONDED = 'N';
        OUTPUT;
     END;
DATA NO_RESP_ORPHANS; SET NO_RESP_ORPHANS;
     PERMIT = PERMIT + 1000000;
     KEEP PERMIT STATUS VENDORCOPY RESPONDED COMMUNITY;
RUN;

DATA PERMITS; SET PERMITS NO_RESP_ORPHANS;
PROC SORT; BY PERMIT;

PROC FREQ DATA = PERMITS;
     TABLE COMMUNITY / NOPRINT OUT=PERMITS_BY_COMMUNITY;
DATA PERMITS_BY_COMMUNITY; SET PERMITS_BY_COMMUNITY;
     PERMITS = COUNT;
     KEEP COMMUNITY PERMITS;
RUN;

PROC SORT DATA = PERMITS; BY RESPONDED;
PROC FREQ DATA = PERMITS; BY RESPONDED;
     TABLE COMMUNITY / NOPRINT OUT=RESPONSE_BY_COMMUNITY;
DATA NONRESPONSE_BY_COMMUNITY; SET RESPONSE_BY_COMMUNITY;
     IF RESPONDED = 'N';
     NONRESPONDANTS = COUNT;
     P_NONRESPONSE = PERCENT;
     KEEP COMMUNITY P_NONRESPONSE NONRESPONDANTS;
RUN;

DATA RESPONDED_BY_COMMUNITY; SET RESPONSE_BY_COMMUNITY;
     IF RESPONDED = 'Y';
     RESPONDANTS = COUNT;
     P_RESPONDED = PERCENT;
     KEEP COMMUNITY P_RESPONDED RESPONDANTS;
RUN;

DATA PERMITS_BY_COMMUNITY; MERGE PERMITS_BY_COMMUNITY NONRESPONSE_BY_COMMUNITY RESPONDED_BY_COMMUNITY; BY COMMUNITY;
     IF NONRESPONDANTS = . THEN NONRESPONDANTS = 0;
     IF RESPONDANTS = . THEN RESPONDANTS = 0;
     IF P_NONRESPONSE = . THEN P_NONRESPONSE = 0;
     IF P_RESPONDED = . THEN P_RESPONDED = 0;
PROC PRINT;
RUN;





PROC SORT DATA = SASDATA.SALMON_HARVEST; BY PERMIT;
PROC SORT DATA = PERMITS; BY PERMIT;
DATA REPORTED; MERGE PERMITS SASDATA.SALMON_HARVEST; BY PERMIT;
     R_RED = RED;    IF R_RED = . THEN R_RED = 0;
     R_KING = KING;  IF R_KING = . THEN R_KING = 0;
     R_COHO = COHO;  IF R_COHO = . THEN R_COHO = 0;
     R_PINK = PINK;  IF R_PINK = . THEN R_PINK = 0;
     R_CHUM = CHUM;  IF R_CHUM = . THEN R_CHUM = 0;
     R_FLOUNDER = FLOUNDER;  IF R_FLOUNDER = . THEN R_FLOUNDER = 0;
     KEEP PERMIT COMMUNITY R_RED R_KING R_COHO R_PINK R_CHUM R_FLOUNDER;

PROC SORT DATA = REPORTED; BY COMMUNITY;
PROC MEANS SUM NOPRINT; BY COMMUNITY;
     VAR R_RED R_KING R_COHO R_PINK R_CHUM R_FLOUNDER;
     OUTPUT OUT = REPORTED_BY_COMMUNITY SUM = R_RED R_KING R_COHO R_PINK R_CHUM R_FLOUNDER; 

PROC PRINT DATA = REPORTED_BY_COMMUNITY;
RUN;

PROC MEANS SUM DATA = REPORTED_BY_COMMUNITY;
     VAR R_RED R_KING R_COHO R_PINK R_CHUM R_FLOUNDER; 
     OUTPUT OUT = TOTAL_REPORTED SUM = TR_RED TR_KING TR_COHO TR_PINK TR_CHUM TR_FLOUNDER;
PROC PRINT DATA = TOTAL_REPORTED;
RUN;

DATA EXPANDED; SET SASDATA.FINAL_ESTIMATES;
/*DATA EXPANDED; SET SASDATA.corrected_final_estimates;*/ *NEEDED FOR 2005;
     IF VARIABLE = 'DAYS' OR VARIABLE = 'TOTAL' THEN DELETE;
     VARIABLE = UPCASE(VARIABLE); 
     *BHH7 = BHH6;  *NEEDED IN 2004;
     KEEP VARIABLE BHH7;
PROC PRINT;
RUN;


PROC TRANSPOSE DATA = EXPANDED OUT = FLIPPED; 
     ID VARIABLE;
     VAR BHH7;

PROC PRINT DATA = FLIPPED;
RUN;

DATA EXPANDED; SET FLIPPED;
     E_RED = RED;  
     E_KING = KING;  
     E_COHO = COHO;  
     E_PINK = PINK;  
     E_CHUM = CHUM; 
     E_FLOUNDER = FLOUNDER; 
     KEEP E_RED E_KING E_COHO E_PINK E_CHUM E_FLOUNDER;
RUN;
PROC PRINT;
RUN;

DATA EXPANSION; MERGE TOTAL_REPORTED EXPANDED;
     EXPANSION_RED = E_RED - TR_RED;  
     EXPANSION_KING = E_KING - TR_KING;  
     EXPANSION_COHO = E_COHO - TR_COHO;  
     EXPANSION_PINK = E_PINK - TR_PINK;  
     EXPANSION_CHUM = E_CHUM - TR_CHUM; 
     EXPANSION_FLOUNDER = E_FLOUNDER - TR_FLOUNDER; 
RUN;
PROC PRINT;
RUN;

DATA FINAL; MERGE PERMITS_BY_COMMUNITY REPORTED_BY_COMMUNITY; BY COMMUNITY;
RUN;

DATA FINAL; MERGE FINAL EXPANSION; BY _TYPE_;
     EXPANDED_RED = R_RED + (EXPANSION_RED * (P_NONRESPONSE/100));
     EXPANDED_KING = R_KING + (EXPANSION_KING * (P_NONRESPONSE/100));
     EXPANDED_COHO = R_COHO + (EXPANSION_COHO * (P_NONRESPONSE/100));
     EXPANDED_PINK = R_PINK + (EXPANSION_PINK * (P_NONRESPONSE/100));
     EXPANDED_CHUM = R_CHUM + (EXPANSION_CHUM * (P_NONRESPONSE/100));
     EXPANDED_FLOUNDER = R_FLOUNDER + (EXPANSION_FLOUNDER * (P_NONRESPONSE/100));
     DROP _TYPE_ _FREQ_  E_RED E_KING E_COHO E_PINK E_CHUM E_FLOUNDER 
                         EXPANSION_RED EXPANSION_KING EXPANSION_COHO EXPANSION_PINK EXPANSION_CHUM EXPANSION_FLOUNDER
                         P_RESPONDED TR_RED TR_KING TR_COHO TR_PINK TR_CHUM TR_FLOUNDER;
RUN;




PROC MEANS SUM DATA = FINAL;
     VAR R_RED R_KING R_COHO R_PINK R_CHUM EXPANDED_RED EXPANDED_KING EXPANDED_COHO EXPANDED_PINK EXPANDED_CHUM EXPANDED_FLOUNDER;
RUN;


PROC SORT DATA = PERMITS; BY COMMUNITY;
PROC FREQ DATA = PERMITS; BY COMMUNITY;
     WHERE RESPONDED = 'Y';
     TABLES FISHED / NOPRINT OUT=FISHED_RESPONDED;
DATA FISHED_RESPONDED; SET FISHED_RESPONDED;
     IF FISHED = 'Y';
     PERMITS_FISHED = COUNT;
     KEEP COMMUNITY PERMITS_FISHED;
RUN;

DATA FINAL; MERGE FINAL FISHED_RESPONDED; BY COMMUNITY;
     IF PERMITS_FISHED = . THEN PERMITS_FISHED = 0;
     MERGEVAR = 1;
RUN;

DATA FISH; SET SASDATA.FISHED_MAILING2;
     MERGEVAR = 1;
     KEEP MERGEVAR P;

DATA FINAL; MERGE FINAL FISH; BY MERGEVAR;
     PERMITS_FISHED = PERMITS_FISHED + (NONRESPONDANTS*P);
PROC PRINT;
RUN;

DATA EXPORT; 
     RETAIN COMMUNITY PERMITS RESPONDANTS NONRESPONDANTS P_NONRESPONSE PERMITS_FISHED R_RED R_KING R_COHO R_PINK R_CHUM R_FLOUNDER
            EXPANDED_RED EXPANDED_KING EXPANDED_COHO EXPANDED_PINK EXPANDED_CHUM EXPANDED_FLOUNDER;
    SET FINAL;
    DROP MERGEVAR P;
RUN;


PROC EXPORT DATA= WORK.EXPORT
            OUTFILE= "O:\DSF\RTS\COMMON\Pat\Permits\Salmon\Subsistence\&YEAR\export.XLS" DBMS=XLS REPLACE;
            SHEET="&YEAR"; 
RUN;




