%LET PROJECT = SALMON;
%LET PROGRAM = ESTIMATES;
%LET YEAR = 2017;
%LET SPECIES = SALMON;
RUN;

TITLE1 "&PROJECT - &YEAR - Nonresponse Problem";

OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
RUN;

LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\NONRESPONSE PROBLEM";


DATA NONRESPONSE; SET SASDATA.FINAL_ESTIMATES_50 SASDATA.FINAL_ESTIMATES_60 SASDATA.FINAL_ESTIMATES_70
                      SASDATA.FINAL_ESTIMATES_80 SASDATA.FINAL_ESTIMATES_90 SASDATA.FINAL_ESTIMATES_100;
     DROP BHH5 SE5;

DATA NONRESPONSE; SET NONRESPONSE; 
      RENAME BHH1 = ESTIMATED_HARVEST_KENAI              SE1 = KENAI_HARVEST_SE
             BHH2 = ESTIMATED_HARVEST_KASILOF_DIPNET     SE2 = KASILOF_DIPNET_HARVEST_SE
             BHH3 = ESTIMATED_HARVEST_KASILOF_GILNET     SE3 = KASILOF_GILLNET_HARVEST_SE
             BHH4 = ESTIMATED_HARVEST_FISH_CREEK         SE4 = FISH_CREEK_HARVEST_SE
             BHH6 = ESTIMATED_HARVEST_UNKNOWN            SE6 = UNKNOWN_HARVEST_SE
             BHH7 = ESTIMATED_HARVEST_TOTAL              SE7 = TOTAL_HARVEST_SE;
RUN;


PROC EXPORT DATA= NONRESPONSE
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\NONRESPONSE PROBLEM\NONRESPONSE" 
            DBMS=EXCELCS REPLACE;
            SHEET="EXPANDED HARVEST2"; 
RUN;


