****************************************************************************************;
*     There are 3 programs to analyze the salmon and shellfish permit databases:       *;
*         1. permits.sas                                                               *;
*         2. harvest.sas                                                               *;
*         3. estimates.sas                                                             *;
*     This program reads and modifies data for permits                                 *;
*     This program is stored as O:\DSF\RTS\common\PAT\PERMITS\salmon\2013\permit.sas   *;
****************************************************************************************;

%LET PROJECT = SALMON;
%LET DATA = cislpm17c;
%LET YEAR = 2017;
%LET PROGRAM = PERMIT;

%LET RESPONSE_RATE = 100;

OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
RUN;

TITLE1 "&PROJECT - &YEAR";

LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR";
DATA LIMITED; SET SASDATA.cislpm17c;
     IF MAILING = 9 THEN DELETE;
     RANDOM = RANUNI(5646);
     MERGEVAR = 1;
RUN;

PROC MEANS NOPRINT DATA = LIMITED; 
     VAR MERGEVAR;
	 OUTPUT OUT = TOTAL_ISSUED N = NHAT;

DATA TOTAL_ISSUED; SET TOTAL_ISSUED (KEEP = NHAT);
     VAR_NHAT = 0;
     MERGEVAR = 1;

DATA LIMITED; MERGE LIMITED TOTAL_ISSUED; BY MERGEVAR;
     DROP MERGEVAR;
RUN;


PROC SORT DATA = LIMITED; BY RANDOM;
DATA LIMITED; SET LIMITED;
     RANK = _N_;
	 IF RANK LE ((&RESPONSE_RATE/100)*NHAT) THEN RESPONDED = 'Y';
	 IF RANK GT ((&RESPONSE_RATE/100)*NHAT) THEN RESPONDED = 'N';
	 IF RESPONDED = 'N' THEN STATUS = 'NON RESPONDENT'; 
	 IF RESPONDED = 'N' THEN MAILING = 9; 
     DROP RANK RANDOM NHAT VAR_NHAT;
RUN; 


LIBNAME SASDATA BASE "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\NONRESPONSE PROBLEM";
DATA SASDATA.cislpm17c; SET LIMITED;
   
RUN;







**************************************************************************;
*                              PERMIT DATA                               *;
**************************************************************************;

DATA SASDATA.&DATA; SET SASDATA.&DATA;
     CITY = UPCASE(CITY);

/*
PROC PRINT DATA = SASDATA.&DATA (OBS=10);
     TITLE2 'PERMIT DATABASE';
     TITLE3 'FIRST 10 RECORDS';
RUN; 

PROC CONTENTS DATA = SASDATA.&DATA;
     TITLE3 '';
RUN;
*/

DATA ISSUED; SET SASDATA.&DATA;
     RENAME STATUS = S;

PROC FREQ DATA = ISSUED;
     TABLES MAILING;
RUN;


DATA ISSUED; SET ISSUED;
     IF S = 'U' THEN STATUS = 'BLANK REPORT    ';
     IF S = 'N' THEN STATUS = 'DID NOT FISH';
     IF S = 'H' THEN STATUS = 'HARVEST REPORTED';
     IF S = 'Z' THEN STATUS = 'NON RESPONDENT';

     IF CITY = 'ANCHORGE' THEN CITY = 'ANCHORAGE';
     IF CITY = 'DENALI NATIONAL PARK' OR CITY = 'DENALI PARKS' THEN CITY = 'DENALI PARK';
     IF CITY = 'EGALE RIVER' THEN CITY = 'EAGLE RIVER';
     IF SUBSTR(CITY,1,6) = 'ELMEND' THEN CITY = 'ELMENDORF AFB';
     IF SUBSTR(CITY,1,6) = 'FORT R' THEN CITY = 'FORT RICHARDSON';

     IF OFFICE = 'NULL' THEN OFFICE = '';
     PERMIT = PERMITNO;
     IF ADDRESS = '' AND PERMIT LT 60000 THEN VENDORCOPY = 'N';
        ELSE VENDORCOPY = 'Y';
     IF S = 'Z' THEN RESPONDED = 'N'; 
        ELSE RESPONDED = 'Y';
     ALLOWED = ((FAMILYSI - 1) * 10) + 25;
     DROP IMAGEPATH PMRECID PHONE KEYDATE COMMENTS YEAR DATEISS PERMITNO S KEYID INITIAL LICENSE_NO;
RUN;

PROC SORT DATA = ISSUED; BY PERMIT;
     TITLE2 'SAS WORK ISSUED DATABASE';
     TITLE3 'CHECKS';
RUN;



DATA ISSUED1; SET ISSUED (DROP = DUPPREF);RUN;

DATA PERSONAL; SET ISSUED;
     KEEP PERMIT ADLNO CITY STATE FIRST_NAME LAST_NAME;

DATA ISSUED; SET ISSUED;
     DROP DUPPREF ADLNO CITY STATE FIRST_NAME LAST_NAME HHMEMBERS;



DATA SASDATA.ISSUED; SET ISSUED;
DATA SASDATA.PERSONAL; SET PERSONAL;

RUN;

DATA ISSUED; SET SASDATA.ISSUED;
     VENDORCOPY = 'Y';   
PROC MEANS SUM DATA=ISSUED NOPRINT;
     CLASS VENDORCOPY RESPONDED MAILING;
     VAR PERMIT;
     OUTPUT OUT = SUMMARY;
RUN;

PROC SORT; BY VENDORCOPY RESPONDED MAILING _TYPE_ _FREQ_;
DATA SUMMARY; SET SUMMARY; BY VENDORCOPY RESPONDED MAILING _TYPE_ _FREQ_;
     IF FIRST._FREQ_;
     DROP PERMIT _STAT_ _TYPE_;

PROC SORT; BY MAILING RESPONDED VENDORCOPY; 
/* 
PROC PRINT DATA = SUMMARY;
     TITLE2 'SUMMARY OF DATA';
     TITLE3 'USED IN ESTIMATING THE NUMBER OF PERMITS ISSUED';
RUN;
*/

DATA TABLE; SET SUMMARY;
     IF VENDORCOPY = 'Y' AND RESPONDED = ' ' AND MAILING = . THEN VYRB = _FREQ_;
     IF VENDORCOPY = 'N' AND RESPONDED = 'Y' AND MAILING = . THEN VNRY = _FREQ_;
     IF VENDORCOPY = 'Y' AND RESPONDED = 'N' AND MAILING = . THEN VYRN = _FREQ_;
     IF VENDORCOPY = 'Y' AND RESPONDED = 'Y' AND MAILING = 0 THEN NUMERATOR = _FREQ_;   
     IF VENDORCOPY = 'Y' AND RESPONDED = ' ' AND MAILING = . THEN DENOMINATOR = _FREQ_;
     IF VYRB = . AND VNRY = . AND VYRN = . AND NUMERATOR = . AND DENOMINATOR = . THEN DELETE;
     KEEP VYRB VNRY VYRN NUMERATOR DENOMINATOR;
DATA TABLE; SET TABLE;
     IF VYRB = . THEN VYRB = 0;
     IF VNRY = . THEN VNRY = 0;
     IF VYRN = . THEN VYRN = 0;
     IF NUMERATOR = . THEN NUMERATOR = 0;
     IF DENOMINATOR = . THEN DENOMINATOR = 0;

PROC PRINT;
RUN;

PROC MEANS SUM NOPRINT;
     VAR VYRB VNRY VYRN NUMERATOR DENOMINATOR;
     OUTPUT OUT = TABLE SUM=; 

DATA TABLE; SET TABLE (DROP = _TYPE_ _FREQ_);
     VOL_RESP_RATE = NUMERATOR/DENOMINATOR;
     VYRY = VYRB - VYRN;
     VNRN = ROUND((VNRY / VOL_RESP_RATE),1);
     VNRB = ROUND((VNRY + VNRN),1);
     VBRY = VYRY + VNRY;
     VBRN = VYRN + VNRN;

     VBRB = VYRY + VNRY + VYRN + VNRN;
     VBRB1 = VBRY + VBRN;
     VBRB2 = VYRB + VNRB;

     VAR_VOL_RESP_RATE = (VOL_RESP_RATE * (1-VOL_RESP_RATE))/(VYRB-1);
     VAR_VNRB = VNRY**2 * (1/(VOL_RESP_RATE**4))*VAR_VOL_RESP_RATE;
     VAR_VBRB = VAR_VNRB;

     DROP NUMERATOR DENOMINATOR;
PROC PRINT;
     TITLE2 'ESTIMATES OF THE NUMBER OF PERMITS ISSUED';
     TITLE3;
RUN;



DATA TOTAL_ISSUED; SET TABLE (KEEP = VBRB  VAR_VBRB);
     RENAME VBRB = NHAT VAR_VBRB = VAR_NHAT;
PROC PRINT;
RUN;

DATA SASDATA.TOTAL_ISSUED; SET TOTAL_ISSUED;
RUN;




