%LET PROJECT = SALMON;

OPTIONS PAGENO=1 NODATE SYMBOLGEN LINESIZE=119 PAGESIZE=67 ;
LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\&PROJECT\2009";

TITLE1 "SALMON - &YEAR";

RUN;




PROC IMPORT OUT= WORK.ONE 
     DATAFILE= "O:\DSF\RTS\PAT\Permits\Salmon\2009\PU PERMITS 2009 EXTRA ESTIMATES.XLS" 
     DBMS=EXCEL REPLACE;
     SHEET="HARVEST_BY_PERMIT$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;

DATA ONE; SET ONE;
     IF SALMON = 0 THEN DO;
	    RED = 0;
		KING = 0;
		COHO = 0;
		PINK = 0;
		CHUM = 0;
     END;

PROC SORT; BY PERMIT;
PROC PRINT DATA = ONE (OBS = 50);
     TITLE2 'DATA ONE';
RUN;

PROC IMPORT OUT= WORK.TWO
     DATAFILE= "O:\DSF\RTS\PAT\Permits\Salmon\2009\PU PERMITS 2009 EXTRA ESTIMATES.XLS" 
     DBMS=EXCEL REPLACE;
     SHEET="HARVEST_BY_PERMIT_AND_FISHERY$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
PROC SORT; BY PERMIT;
PROC PRINT DATA = TWO (OBS = 50);
     TITLE2 'DATA TWO';
RUN;



PROC IMPORT OUT= WORK.THREE
     DATAFILE= "O:\DSF\RTS\PAT\Permits\Salmon\2009\PU PERMITS 2009 EXTRA ESTIMATES.XLS" 
     DBMS=EXCEL REPLACE;
     SHEET="FISHERIES_BY_PERMIT$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
PROC SORT; BY PERMIT;
PROC PRINT DATA = THREE (OBS = 50);
     TITLE2 'DATA THREE';
RUN;

DATA TWO; SET TWO;
     SALMON = SUM(OF RED KING COHO PINK CHUM);
DATA KENAI; SET TWO;
     IF FISHERY = 'KENAI';
	 KENAI_HARVEST = SALMON;
	 KENAI_DAYS = DAYS;
	 KEEP PERMIT KENAI_HARVEST KENAI_DAYS;
DATA KASILOF_DIPNET; SET TWO;
     IF FISHERY = 'KASILOF DIPNET';
	 KASILOF_DIPNET_HARVEST = SALMON;
	 KASILOF_DIPNET_DAYS = DAYS;
	 KEEP PERMIT KASILOF_DIPNET_HARVEST KASILOF_DIPNET_DAYS;
DATA KASILOF_GILLNET; SET TWO;
     IF FISHERY = 'KASILOF GILLNET';
	 KASILOF_GILLNET_HARVEST = SALMON;
	 KASILOF_GILLNET_DAYS = DAYS;
	 KEEP PERMIT KASILOF_GILLNET_HARVEST KASILOF_GILLNET_DAYS;
DATA UNKNOWN; SET TWO;
     IF FISHERY = 'UNKNOWN';
	 UNKNOWN_HARVEST = SALMON;
	 UNKNOWN_DAYS = DAYS;
	 KEEP PERMIT UNKNOWN_HARVEST UNKNOWN_DAYS;

DATA FISHERY_HARVEST; MERGE KENAI KASILOF_DIPNET KASILOF_GILLNET UNKNOWN; BY PERMIT;
PROC PRINT DATA = FISHERY_HARVEST (OBS = 50);
RUN;


DATA ALL; MERGE ONE THREE FISHERY_HARVEST; BY PERMIT;
     IF KENAI_HARVEST = . THEN DO; KENAI_HARVEST = 0; KENAI_DAYS = 0; END;
     IF KASILOF_DIPNET_HARVEST = . THEN DO; KASILOF_DIPNET_HARVEST = 0; KASILOF_DIPNET_DAYS = 0; END;
     IF KASILOF_GILLNET_HARVEST = . THEN DO; KASILOF_GILLNET_HARVEST = 0; KASILOF_GILLNET_DAYS = 0; END;
     IF UNKNOWN_HARVEST = . THEN DO; UNKNOWN_HARVEST = 0; UNKNOWN_DAYS = 0; END;
	 IF FISHERIES = . THEN FISHERIES = 0;
	 TOTAL_DAYS = KENAI_DAYS + KENAI_DAYS + KASILOF_GILLNET_DAYS + UNKNOWN_DAYS;
	 HOUSEHOLD_SIZE = ((ALLOWED - 25) / 10) + 1;
	 YEAR = 2009;
	 DROP FISHERY1 FISHERY2 FISHERY3 F10;
PROC PRINT DATA = ALL (OBS = 50);
RUN;

DATA SASDATA.EXTRA2009; SET ALL;


/*
LIBNAME SASDATA BASE "O:\DSF\RTS\Pat\Permits\Salmon\REPORT 2007-2009";

DATA EXTRA_2007_2008_2009; SET SASDATA.EXTRA2007 SASDATA.EXTRA2008 SASDATA.EXTRA2009;
     IF FISHERIES EQ 1;

PROC EXPORT DATA= WORK.EXTRA_2007_2008_2009 
     OUTFILE= "O:\DSF\RTS\PAT\Permits\Salmon\REPORT 2007-2009\MORE EXTRA ESTIMATES.xls" 
     DBMS=EXCEL REPLACE;
     SHEET="DATA"; 
RUN;
*/

/*
PROC DATASETS KILL;
RUN;
*/
