OPTIONS PAGENO=1 NODATE SYMBOLGEN LINESIZE=119 PAGESIZE=67 ;
%LET PROJECT = SALMON;


LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\&PROJECT\2007";
RUN;

DATA DID_NOT_FISH; SET SASDATA.ISSUED;
     IF STATUS = 'DID NOT FISH';
     KEEP PERMIT STATUS FAMILYSI ALLOWED;

DATA PERSONAL; SET SASDATA.PERSONAL;
     KEEP PERMIT CITY;

DATA PERSONAL2; MERGE PERSONAL DID_NOT_FISH; BY PERMIT;
     IF STATUS = 'DID NOT FISH';
PROC SORT DATA = PERSONAL2; BY CITY;

DATA CITY; SET SASDATA.CITIES;
PROC SORT DATA = CITY; BY CITY;

DATA LOCATION; MERGE CITY PERSONAL2; BY CITY;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;
     IF PERMIT = . THEN DELETE;

DATA LOCATION; SET LOCATION;
     IF CITY = ' ' THEN REGION = 4;
     DROP NEW_NAME;
	 YEAR = 2007;

PROC EXPORT DATA= WORK.LOCATION
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\REPORT 2007-2009\DID NOT FISH.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="2007"; 
RUN;



LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\&PROJECT\2008";
RUN;

DATA DID_NOT_FISH; SET SASDATA.ISSUED;
     IF STATUS = 'DID NOT FISH';
     KEEP PERMIT STATUS FAMILYSI ALLOWED;

DATA PERSONAL; SET SASDATA.PERSONAL;
     KEEP PERMIT CITY;

DATA PERSONAL2; MERGE PERSONAL DID_NOT_FISH; BY PERMIT;
     IF STATUS = 'DID NOT FISH';
PROC SORT DATA = PERSONAL2; BY CITY;

DATA CITY; SET SASDATA.CITIES;
PROC SORT DATA = CITY; BY CITY;

DATA LOCATION; MERGE CITY PERSONAL2; BY CITY;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;
     IF PERMIT = . THEN DELETE;

DATA LOCATION; SET LOCATION;
     IF CITY = ' ' THEN REGION = 4;
     DROP NEW_NAME;
	 YEAR = 2008;

PROC EXPORT DATA= WORK.LOCATION
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\REPORT 2007-2009\DID NOT FISH.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="2008"; 
RUN;









LIBNAME SASDATA BASE "O:\DSF\RTS\PAT\PERMITS\&PROJECT\2009";
RUN;

DATA DID_NOT_FISH; SET SASDATA.ISSUED;
     IF STATUS = 'DID NOT FISH';
     KEEP PERMIT STATUS FAMILYSI ALLOWED;

DATA PERSONAL; SET SASDATA.PERSONAL;
     KEEP PERMIT CITY;

DATA PERSONAL2; MERGE PERSONAL DID_NOT_FISH; BY PERMIT;
     IF STATUS = 'DID NOT FISH';
PROC SORT DATA = PERSONAL2; BY CITY;

DATA CITY; SET SASDATA.CITIES;
PROC SORT DATA = CITY; BY CITY;

DATA LOCATION; MERGE CITY PERSONAL2; BY CITY;
     IF AREA = '1' THEN AREA = '';
     IF NEW_NAME NE ' ' THEN DO;
                               CITY = NEW_NAME;
                             END;
     IF PERMIT = . THEN DELETE;

DATA LOCATION; SET LOCATION;
     IF CITY = ' ' THEN REGION = 4;
     DROP NEW_NAME;
	 YEAR = 2009;

PROC EXPORT DATA= WORK.LOCATION
            OUTFILE= "O:\DSF\RTS\PAT\PERMITS\&PROJECT\REPORT 2007-2009\DID NOT FISH.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="2009"; 
RUN;


