****************************************************************************************;
*     There are 3 programs to analyze the salmon and shellfish permit databases:       *;
*         1. permits.sas                                                               *;
*         2. harvest.sas                                                               *;
*         3. estimates.sas                                                             *;
*     This program reads and modifies data for harvest                                 *;
*     This program is stored as S:\RTS\common\Pat\Permits\Chitna\2010\harvest.sas  *;
****************************************************************************************;



%LET PROJECT = SALMON;
%LET DATA = cislhv18c;
%LET YEAR = 2018;


%LET SPECIES_COMMA = RED,KING,COHO,PINK,CHUM,FLOUNDER; 
%LET SPECIES_LIST = RED KING COHO PINK CHUM FLOUNDER; 
%LET PROGRAM = HARVEST;
%LET GILLNET_START = '15JUN18'D; 
%LET GILLNET_STOP = '24JUN18'D;
%LET KENAI_KING_START = '25JUL18'D; 
%LET KENAI_KING_STOP = '31JUL18'D; 


OPTIONS PAGENO=1 SYMBOLGEN PAGESIZE = 68 LINESIZE = 150;
LIBNAME SASDATA BASE "O:\DSF\RTS\common\Pat\Permits\&PROJECT\&YEAR";
RUN;


TITLE1 "&PROJECT - &YEAR";


**************************************************************************;
*                              HARVEST DATA                              *;
**************************************************************************;

PROC CONTENTS DATA = SASDATA.&DATA;
RUN;

PROC FREQ DATA = SASDATA.&DATA;
     TABLES nohrvrpt FISHERY EDITED;
RUN;


DATA HARVEST; SET SASDATA.&DATA (RENAME=(PERMITNO = PERMIT));
	 DROP imagepath YEAR KEYDATE HVRECID MAILING KEYID EDITED COMMENTS;
OPTIONS VALIDVARNAME=UPCASE;

DATA HARVEST; SET HARVEST;
     MONTH = MONTH(HARVDATE);
	 DAY = DAY(HARVDATE);
     SPECIES = 'SALMON';  
     IF NOCATCH = 1 THEN CATCH = 'N'; IF NOCATCH NE 1 THEN CATCH = 'Y';
     IF NOHRVRPT = 1 THEN HRVRPT = 'N'; IF NOHRVRPT NE 1 THEN HRVRPT = 'Y';
     IF FISHERY = '' THEN FISHERY = 'UNKNOWN';
     RESPONDED = 'Y';
     WEEK = INTCK('WEEK',INTNX('YEAR', HARVDATE, 0), HARVDATE) + 1;

     IF RED = . THEN RED = 0;  IF KING = . THEN KING = 0; IF COHO = . THEN COHO = 0;
     IF PINK = . THEN PINK = 0;  IF CHUM = . THEN CHUM = 0;  IF FLOUNDER = . THEN FLOUNDER = 0;

     DROP NOHRVRPT NOCATCH;
RUN;



DATA HARVEST; SET HARVEST; 
     IF PERMIT = 82913 AND MONTH = 7 AND DAY = 8 AND FISHERY = 'KASILOF' THEN DO;  FIX = 1;  END;
     IF PERMIT = 80947 AND MONTH = 6 AND DAY = 15 AND FISHERY = 'KASILOF' THEN DO;  FIX = 2;  END;
     IF PERMIT = 80290 AND MONTH = 7 AND DAY = 1 AND FISHERY = 'KASILOF' THEN DO;  FIX = 2;  END;
     IF PERMIT = 82417 AND MONTH = 7 AND DAY = 2 AND FISHERY = 'KASILOF' THEN DO;  FIX = 2;  END;
     IF PERMIT = 82417 AND MONTH = 7 AND DAY = 3 AND FISHERY = 'KASILOF' THEN DO;  FIX = 2;  END;
     IF PERMIT = 16934 AND MONTH = 7 AND DAY = 6 AND FISHERY = 'KASILOF' THEN DO;  FIX = 2;  END;
     IF PERMIT = 16934 AND MONTH = 7 AND DAY = 8 AND FISHERY = 'KASILOF' THEN DO;  FIX = 2;  END;
     IF PERMIT = 5686 AND MONTH = 7 AND DAY = 12 AND FISHERY = 'KENAI' THEN DO;  FIX = 2;  END;
     IF PERMIT = 5686 AND MONTH = 7 AND DAY = 13 AND FISHERY = 'KENAI' THEN DO;  FIX = 2;  END;
     IF PERMIT = 81455 AND MONTH = 7 AND DAY = 18 AND FISHERY = 'KASILOF' THEN DO;  FIX = 2;  END;
     IF PERMIT = 18521 AND MONTH = 7 AND DAY = 19 AND FISHERY = 'KASILOF' THEN DO;  FIX = 2;  END;
     IF PERMIT = 16079 AND MONTH = 7 AND DAY = 19 AND FISHERY = 'KENAI' THEN DO;  FIX = 2;  END;
     IF PERMIT = 80435 AND MONTH = 7 AND DAY = 19 AND FISHERY = 'KASILOF' THEN DO;  FIX = 2;  END;
     IF PERMIT = 82456 AND MONTH = 7 AND DAY = 21 AND FISHERY = 'KASILOF' THEN DO;  FIX = 3;  END;
     IF PERMIT = 16079 AND MONTH = 7 AND DAY = 27 AND FISHERY = 'KENAI' THEN DO;  FIX = 3;  END;
     IF PERMIT = 5775 AND MONTH = 7 AND DAY = 27 AND FISHERY = 'KENAI' THEN DO;  FIX = 3;  END;
     IF PERMIT = 15511 AND MONTH = 7 AND DAY = 29 AND FISHERY = 'KENAI' THEN DO;  FIX = 3;  END;
     IF PERMIT = 18529 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'KASILOF' THEN DO;  FIX = 3;  END;
     IF PERMIT = 716 AND MONTH = 6 AND DAY = 27 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 14272 AND MONTH = 7 AND DAY = 11 AND FISHERY = 'KENAI' THEN DO;  FIX = 4;  END;
     IF PERMIT = 2703 AND MONTH = 7 AND DAY = 16 AND FISHERY = 'KENAI' THEN DO;  FIX = 4;  END;
     IF PERMIT = 2704 AND MONTH = 7 AND DAY = 16 AND FISHERY = 'KENAI' THEN DO;  FIX = 4;  END;
     IF PERMIT = 716 AND MONTH = 7 AND DAY = 17 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 10028 AND MONTH = 7 AND DAY = 18 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 81684 AND MONTH = 7 AND DAY = 21 AND FISHERY = 'KENAI' THEN DO;  FIX = 4;  END;
     IF PERMIT = 4929 AND MONTH = 7 AND DAY = 23 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 6475 AND MONTH = 7 AND DAY = 25 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 6471 AND MONTH = 7 AND DAY = 25 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 6476 AND MONTH = 7 AND DAY = 25 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 7897 AND MONTH = 7 AND DAY = 26 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 3630 AND MONTH = 7 AND DAY = 26 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 60370 AND MONTH = 7 AND DAY = 26 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 716 AND MONTH = 7 AND DAY = 26 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 14272 AND MONTH = 7 AND DAY = 26 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;
     IF PERMIT = 81684 AND MONTH = 8 AND DAY = 3 AND FISHERY = 'KASILOF' THEN DO;  FIX = 4;  END;

     IF PERMIT = 93392 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 6329 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 93464 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 12212 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 93471 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 92719 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 24543 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 12255 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 88128 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 9676 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 9365 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 5929 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 24558 AND MONTH = 7 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 17923 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 93462 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 82120 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 9678 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 92445 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 87986 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 85726 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 85722 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 86829 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 10095 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 83872 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 93550 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 84191 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 91218 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 93565 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 24548 AND MONTH = 7 AND DAY = 31 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 88919 AND MONTH = 8 AND DAY = 3 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 60497 AND MONTH = 8 AND DAY = 7 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 92999 AND MONTH = 8 AND DAY = 11 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 10097 AND MONTH = 8 AND DAY = 25 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 93446 AND MONTH = 8 AND DAY = 29 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
     IF PERMIT = 93446 AND MONTH = 8 AND DAY = 30 AND FISHERY = 'FISH CREEK' THEN DO;  FIX = 5;  END;
RUN;

 
DATA HARVEST; SET HARVEST;   ************************************************************INSTRUCTIONS FROM KRISSY;
     IF FIX = . AND KING GE 1 AND KING GT RED THEN DO;
	                                 OLDKING = KING;
									 OLDRED = RED;
	                                 RED = RED + KING;
                                     KING = 0;
		                             CHANGE = 'Y';
									 FIX = 6;
							  END;
RUN;

DATA HARVEST; SET HARVEST;   ************************************************************INSTRUCTIONS FROM ADAM;
     IF FIX = . AND COHO GE 1 AND COHO GT RED THEN DO;
	                                 OLDCOHO = COHO;
									 OLDRED = RED;
	                                 RED = RED + COHO;
                                     COHO = 0;
		                             CHANGE = 'Y';
									 FIX = 7;
							  END;
RUN;

DATA HARVEST; SET HARVEST;
     IF FIX = 1 THEN DO; OLDPINK = PINK; OLDKING = KING; PINK = PINK + KING; KING = 0; CHANGE = 'Y'; END;
     IF FIX = 2 THEN DO; OLDRED = RED; OLDCOHO = COHO; RED = RED + COHO; COHO = 0; CHANGE = 'Y'; END;
     IF FIX = 3 THEN DO; OLDPINK = PINK; OLDCOHO = COHO; PINK = PINK + COHO; COHO = 0; CHANGE = 'Y'; END;
     IF FIX = 4 THEN DO; OLDRED = RED; OLDCHUM = CHUM; RED = RED + CHUM; CHUM = 0; CHANGE = 'Y'; END;
     IF FIX = 5 THEN DO; OLDRED = RED; OLDCHUM = CHUM; RED = RED + CHUM; CHUM = 0; CHANGE = 'Y'; END;
     DROP MONTH DAY SPECIES;
PROC SORT DATA = HARVEST; BY FIX PERMIT;
RUN;

PROC PRINT DATA = HARVEST;
     WHERE CHANGE = 'Y';
     TITLE2 'DATA CORRECTIONS';
RUN;

PROC FREQ DATA = HARVEST;
     WHERE CHANGE = 'Y';
	 TABLES FIX;
RUN;

PROC CONTENTS DATA = HARVEST;
RUN;
DATA DATA_CHANGED; SET HARVEST;
     IF FIX GT 0;
RUN;

DATA HARVEST; SET HARVEST;
     DROP FIX CHANGE OLDRED OLDCOHO OLDPINK OLDCHUM;
RUN;





DATA HARVEST; SET HARVEST;
     MONTH = MONTH(HARVDATE);
     DAY = DAY(HARVDATE);
     IF FISHERY = 'KENAI' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KENAI' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 6 AND DAY LT 15 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 8 AND DAY GT 7 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'UNKNOWN' AND MONTH = 6 AND DAY GE 15 THEN FISHERY = 'KASILOF';
     IF FISHERY = 'UNKNOWN' AND MONTH = 7 AND DAY LE 9 THEN FISHERY = 'KASILOF';
     IF FISHERY = 'UNKNOWN' AND MONTH = 8 AND DAY GE 1 AND DAY LE 7 THEN FISHERY = 'KASILOF';
RUN;

PROC SORT DATA = HARVEST; BY PERMIT MONTH DAY FISHERY;
RUN;


PROC FREQ;
     TABLES CATCH HRVRPT HARVDATE FISHERY;
RUN;

PROC FREQ DATA = HARVEST;
     TABLES PERMIT / NOPRINT OUT=FREQ_DAYS;
PROC FREQ;
     TABLES COUNT / NOPRINT OUT=FREQ_DAYS;
DATA FREQ_DAYS; SET FREQ_DAYS;
     RENAME COUNT = DAYS_FISHED;
     
PROC PRINT NOOBS DATA = FREQ_DAYS;
     TITLE2 'FREQUENCY OF DAYS FISHED';
     TITLE3 ;
RUN;

PROC FREQ DATA = HARVEST;
     TABLES &SPECIES_LIST;
     TITLE2 'HARVEST DATABASE';
     TITLE3 ;
run;

DATA HARVEST; SET HARVEST;
     DROP MONTH DAY;
PROC SORT DATA = HARVEST; BY PERMIT HARVDATE;
RUN;
     
DATA SASDATA.SALMON_HARVEST; SET HARVEST; 
RUN;


DATA RECORDS1; SET HARVEST;
     IF _N_ LE 10000;
RUN;
DATA RECORDS2; SET HARVEST;
     IF _N_ GT 10000 AND _N_ LE 20000;
RUN;
DATA RECORDS3; SET HARVEST;
     IF _N_ GT 20000;
RUN;



/*
DATA COMMENTS; SET SASDATA.&DATA;
     WHERE COMMENTS NE '';
     KEEP PERMITNO COMMENTS;
RUN;

PROC EXPORT DATA= WORK.COMMENTS
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="HARVEST COMMENTS"; 
RUN;
*/
PROC EXPORT DATA= WORK.RECORDS1
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\& YEAR PU PERMITS" 
            DBMS=EXCELCS REPLACE;
            SHEET="RECORDS1"; 
RUN;
PROC EXPORT DATA= WORK.RECORDS2
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\& YEAR PU PERMITS" 
            DBMS=EXCELCS REPLACE;
            SHEET="RECORDS2"; 
RUN;
PROC EXPORT DATA= WORK.RECORDS3
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\& YEAR PU PERMITS" 
            DBMS=EXCELCS REPLACE;
            SHEET="RECORDS3"; 
RUN;

PROC EXPORT DATA= WORK.DATA_CHANGED
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\& YEAR PU PERMITS" 
            DBMS=EXCELCS REPLACE;
            SHEET="DATA CHANGED"; 
RUN;






/*
DATA GOOD_DATES_ONLY; SET SASDATA.SALMON_HARVEST;
     YEAR = YEAR(HARVDATE);
     IF YEAR = 2017;
     MONTH = MONTH(HARVDATE);
     IF MONTH GT 1;
RUN;


PROC SORT DATA = GOOD_DATES_ONLY; BY HARVDATE FISHERY;
PROC MEANS DATA = GOOD_DATES_ONLY SUM NOPRINT; BY HARVDATE FISHERY;
     VAR RED PINK COHO CHUM KING FLOUNDER;
     OUTPUT OUT = DAILY SUM = SUM_RED SUM_PINK SUM_COHO SUM_CHUM SUM_KING SUM_FLOUNDER MEAN = MEAN_RED MEAN_PINK MEAN_COHO MEAN_CHUM MEAN_KING MEAN_FLOUNDER STDERR = SE_RED SE_PINK SE_COHO SE_CHUM SE_KING SE_FLOUNDER;

DATA DAILY; SET DAILY (DROP= _TYPE_ _FREQ_);
     LOCATION = FISHERY;
     DROP FISHERY;

DATA DAILY; SET DAILY;
     LENGTH FISHERY $18.;
     IF LOCATION EQ 'KASILOF' AND HARVDATE GE &GILLNET_START AND HARVDATE LE &GILLNET_STOP THEN FISHERY = 'KASILOF GILLNET';  *GILLNET;
     IF LOCATION EQ 'KASILOF' AND FISHERY = '' THEN FISHERY = 'KASILOF DIPNET';  *DIPNET;
     IF FISHERY = '' THEN FISHERY = LOCATION;
     DROP LOCATION;
PROC SORT; BY FISHERY HARVDATE;
PROC PRINT DATA = DAILY (OBS = 25);
RUN;



PROC EXPORT DATA= WORK.DAILY 
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\Salmon\&YEAR\DAILY REPORTED.xls" 
            DBMS=EXCELCS REPLACE;
            SHEET="DAILY HARVEST"; 

RUN;
*/



/*
DATA COMMENTS; SET SASDATA.&DATA;
     WHERE COMMENTS NE '';
     KEEP PERMITNO COMMENTS;

PROC EXPORT DATA= WORK.COMMENTS 
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="HARVEST COMMENTS"; 
RUN;

PROC EXPORT DATA= WORK.HARVEST
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="HARVEST RECORDS"; 
RUN;

PROC EXPORT DATA= WORK.WEEKLY
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="WEEKLY REPORTED HARVEST"; 
RUN;
*/
