****************************************************************************************;
*     There are 3 programs to analyze the salmon and shellfish permit databases:       *;
*         1. permits.sas                                                               *;
*         2. harvest.sas                                                               *;
*         3. estimates.sas                                                             *;
*     This program reads and modifies data for harvest                                 *;
*     This program is stored as S:\RTS\common\Pat\Permits\Chitna\2010\harvest.sas  *;
****************************************************************************************;



%LET PROJECT = SALMON;
%LET DATA = cislhv18c;
%LET YEAR = 2018;


%LET SPECIES_COMMA = RED,KING,COHO,PINK,CHUM,FLOUNDER; 
%LET SPECIES_LIST = RED KING COHO PINK CHUM FLOUNDER; 
%LET PROGRAM = HARVEST;
%LET GILLNET_START = '15JUN18'D; 
%LET GILLNET_STOP = '24JUN18'D;
%LET KENAI_KING_START = '25JUL18'D; 
%LET KENAI_KING_STOP = '31JUL18'D; 


OPTIONS PAGENO=1 SYMBOLGEN PAGESIZE = 68 LINESIZE = 150;
LIBNAME SASDATA BASE "O:\DSF\RTS\common\Pat\Permits\&PROJECT\&YEAR";
RUN;


TITLE1 "&PROJECT - &YEAR";


**************************************************************************;
*                              HARVEST DATA                              *;
**************************************************************************;

PROC CONTENTS DATA = SASDATA.&DATA;
RUN;

PROC FREQ DATA = SASDATA.&DATA;
     TABLES nohrvrpt FISHERY EDITED;
RUN;


DATA HARVEST; SET SASDATA.&DATA (RENAME=(PERMITNO = PERMIT));
	 DROP imagepath YEAR KEYDATE HVRECID MAILING KEYID EDITED COMMENTS;
OPTIONS VALIDVARNAME=UPCASE;

DATA HARVEST; SET HARVEST;
     SPECIES = 'SALMON';  
     IF NOCATCH = 1 THEN CATCH = 'N'; IF NOCATCH NE 1 THEN CATCH = 'Y';
     IF NOHRVRPT = 1 THEN HRVRPT = 'N'; IF NOHRVRPT NE 1 THEN HRVRPT = 'Y';
     IF FISHERY = '' THEN FISHERY = 'UNKNOWN';
     RESPONDED = 'Y';
     WEEK = INTCK('WEEK',INTNX('YEAR', HARVDATE, 0), HARVDATE) + 1;

     IF RED = . THEN RED = 0;  IF KING = . THEN KING = 0; IF COHO = . THEN COHO = 0;
     IF PINK = . THEN PINK = 0;  IF CHUM = . THEN CHUM = 0;  IF FLOUNDER = . THEN FLOUNDER = 0;

     DROP NOHRVRPT NOCATCH;
RUN;

/*
DATA HARVEST; SET HARVEST;
     JUNK = 1;
RUN;

ODS GRAPHICS ON;
PROC UNIVARIATE DATA = HARVEST NORMAL PLOT; BY JUNK;
     VAR RED KING COHO PINK CHUM FLOUNDER;
ODS GRAPHICS OFF;
RUN;

PROC BOXPLOT;
     PLOT (RED KING COHO PINK CHUM FLOUNDER) *JUNK;* KING COHO PINK CHUM FLOUNDER;
RUN;
*/

/*
PROC FREQ;
     TABLES RED KING COHO PINK CHUM FLOUNDER;
RUN;
*/


DATA HARVEST; SET HARVEST;     
PROC SORT; BY FISHERY HARVDATE;

DATA COHO_PROBLEM; SET HARVEST;
     IF COHO GE 1 AND COHO GT RED;
PROC PRINT DATA = COHO_PROBLEM;
     TITLE2 'COHO HARVEST GT 0 AND GREATER THAN RED HARVEST';
RUN;

DATA KING_PROBLEM; SET HARVEST;
     IF KING GE 1 AND KING GT RED;
PROC PRINT DATA = KING_PROBLEM;
     TITLE2 'KING HARVEST GT 0 AND GREATER THAN RED HARVEST';
RUN;






DATA HARVEST; SET HARVEST;   ************************************************************INSTRUCTIONS FROM KRISSY;
     IF KING GE 1 AND KING GT RED THEN DO;
	                                 RED = RED + KING;
                                     KING = 0;
							  END;
RUN;

DATA HARVEST; SET HARVEST;   ************************************************************INSTRUCTIONS FROM ADAM;
     IF COHO GE 1 AND COHO GT RED THEN DO;
	                                 RED = RED + COHO;
                                     COHO = 0;
							  END;
RUN;

PROC PRINT DATA = HARVEST;
     WHERE KING GT 0;
     TITLE2 'KING HARVEST GT 0 AFTER CORRECTIONS';
RUN;
PROC PRINT DATA = HARVEST;
     WHERE COHO GT 0;
     TITLE2 'COHO HARVEST GT 0 AFTER CORRECTIONS';
RUN;
PROC FREQ;
     TABLES RED KING COHO PINK CHUM FLOUNDER;
RUN;





DATA HARVEST; SET HARVEST;
     MONTH = MONTH(HARVDATE);
     DAY = DAY(HARVDATE);
     IF FISHERY = 'KENAI' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KENAI' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 6 AND DAY LT 15 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 8 AND DAY GT 7 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'UNKNOWN' AND MONTH = 6 AND DAY GE 15 THEN FISHERY = 'KASILOF';
     IF FISHERY = 'UNKNOWN' AND MONTH = 7 AND DAY LE 9 THEN FISHERY = 'KASILOF';
     IF FISHERY = 'UNKNOWN' AND MONTH = 8 AND DAY GE 1 AND DAY LE 7 THEN FISHERY = 'KASILOF';
RUN;

PROC SORT DATA = HARVEST; BY PERMIT MONTH DAY FISHERY;
RUN;


PROC FREQ;
     TABLES CATCH HRVRPT HARVDATE FISHERY;
RUN;

PROC FREQ DATA = HARVEST;
     TABLES PERMIT / NOPRINT OUT=FREQ_DAYS;
PROC FREQ;
     TABLES COUNT / NOPRINT OUT=FREQ_DAYS;
DATA FREQ_DAYS; SET FREQ_DAYS;
     RENAME COUNT = DAYS_FISHED;
     
PROC PRINT NOOBS DATA = FREQ_DAYS;
     TITLE2 'FREQUENCY OF DAYS FISHED';
     TITLE3 ;
RUN;

PROC FREQ DATA = HARVEST;
     TABLES &SPECIES_LIST;
     TITLE2 'HARVEST DATABASE';
     TITLE3 ;
run;


     
DATA SASDATA.SALMON_HARVEST; SET HARVEST; 
RUN;







DATA COMMENTS; SET SASDATA.&DATA;
     WHERE COMMENTS NE '';
     KEEP PERMITNO COMMENTS;
RUN;

PROC EXPORT DATA= WORK.COMMENTS
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="HARVEST COMMENTS"; 
RUN;

PROC EXPORT DATA= WORK.HARVEST
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="HARVEST RECORDS"; 
RUN;

PROC EXPORT DATA= WORK.KING_PROBLEM
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="KING HARVEST PROBLEMS"; 
RUN;

PROC EXPORT DATA= WORK.COHO_PROBLEM
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="COHO HARVEST PROBLEMS"; 
RUN;






/*
DATA GOOD_DATES_ONLY; SET SASDATA.SALMON_HARVEST;
     YEAR = YEAR(HARVDATE);
     IF YEAR = 2017;
     MONTH = MONTH(HARVDATE);
     IF MONTH GT 1;
RUN;


PROC SORT DATA = GOOD_DATES_ONLY; BY HARVDATE FISHERY;
PROC MEANS DATA = GOOD_DATES_ONLY SUM NOPRINT; BY HARVDATE FISHERY;
     VAR RED PINK COHO CHUM KING FLOUNDER;
     OUTPUT OUT = DAILY SUM = SUM_RED SUM_PINK SUM_COHO SUM_CHUM SUM_KING SUM_FLOUNDER MEAN = MEAN_RED MEAN_PINK MEAN_COHO MEAN_CHUM MEAN_KING MEAN_FLOUNDER STDERR = SE_RED SE_PINK SE_COHO SE_CHUM SE_KING SE_FLOUNDER;

DATA DAILY; SET DAILY (DROP= _TYPE_ _FREQ_);
     LOCATION = FISHERY;
     DROP FISHERY;

DATA DAILY; SET DAILY;
     LENGTH FISHERY $18.;
     IF LOCATION EQ 'KASILOF' AND HARVDATE GE &GILLNET_START AND HARVDATE LE &GILLNET_STOP THEN FISHERY = 'KASILOF GILLNET';  *GILLNET;
     IF LOCATION EQ 'KASILOF' AND FISHERY = '' THEN FISHERY = 'KASILOF DIPNET';  *DIPNET;
     IF FISHERY = '' THEN FISHERY = LOCATION;
     DROP LOCATION;
PROC SORT; BY FISHERY HARVDATE;
PROC PRINT DATA = DAILY (OBS = 25);
RUN;



PROC EXPORT DATA= WORK.DAILY 
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\Salmon\&YEAR\DAILY REPORTED.xls" 
            DBMS=EXCELCS REPLACE;
            SHEET="DAILY HARVEST"; 

RUN;
*/



/*
DATA COMMENTS; SET SASDATA.&DATA;
     WHERE COMMENTS NE '';
     KEEP PERMITNO COMMENTS;

PROC EXPORT DATA= WORK.COMMENTS 
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="HARVEST COMMENTS"; 
RUN;

PROC EXPORT DATA= WORK.HARVEST
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="HARVEST RECORDS"; 
RUN;

PROC EXPORT DATA= WORK.WEEKLY
            OUTFILE= "O:\DSF\RTS\common\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS &YEAR" 
            DBMS=EXCELCS REPLACE;
            SHEET="WEEKLY REPORTED HARVEST"; 
RUN;
*/
