%LET PROJECT = SALMON;
%LET PROGRAM = EXTRA ESTIMATES;
%LET YEAR = 2004;
%LET SPECIES = SALMON;
%LET SPECIES_COMMA = RED,KING,COHO,PINK,CHUM; 
%LET SPECIES_LIST = RED KING COHO PINK CHUM; 

%LET GILLNET_START = '15JUN04'D; 
%LET GILLNET_STOP = '24JUN04'D; 
RUN;

TITLE1 "&PROJECT - &YEAR";

OPTIONS PAGENO=1 NODATE SYMBOLGEN LINESIZE=119 PAGESIZE=67 ;
LIBNAME SASDATA BASE "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
RUN;



PROC SORT DATA=SASDATA.SALMON_HARVEST; BY PERMIT; RUN;  
PROC SORT DATA=SASDATA.ISSUED; BY PERMIT; RUN;

DATA ALLPERMITS; MERGE SASDATA.SALMON_HARVEST SASDATA.ISSUED ; BY PERMIT;  
RUN;

DATA ALLPERMITS2; MERGE ALLPERMITS SASDATA.PERSONAL; BY PERMIT;
     RENAME FISHERY = LOCATION;
     DROP ADLNO FAMILYSI SPECIES OFFICE VENDORCOPY INITIAL KEYID LICENSE_NO STATE;

DATA ALLPERMITS3; SET ALLPERMITS2;
     IF RESPONDED = 'Y';
     IF LOCATION EQ 'KASILOF' AND HARVDATE GE &GILLNET_START AND HARVDATE LE &GILLNET_STOP THEN FISHERY = 'KASILOF GILLNET';  *GILLNET;
     IF LOCATION EQ 'KASILOF' AND FISHERY = '' THEN FISHERY = 'KASILOF DIPNET';  *DIPNET;
     IF LOCATION EQ 'UNK FIXABLE' THEN FISHERY = 'UNKNOWN';
     IF LOCATION EQ 'UNK' THEN FISHERY = 'UNKNOWN';
     IF FISHERY = '' THEN FISHERY = LOCATION;
     MONTH = MONTH(HARVDATE);
     DAY = DAY(HARVDATE);
     DROP LOCATION;
RUN;
PROC CONTENTS;
RUN;

PROC SORT DATA = ALLPERMITS3; BY FISHERY;
PROC FREQ DATA = ALLPERMITS3; BY FISHERY;
     TABLES CITY / OUT = FISHERY_BY_CITY;
     TITLE2 'TRIPS BY CITY AND FISHERY';
RUN;


PROC FREQ DATA = ALLPERMITS3; 
     WHERE FISHERY NE '';
     TABLES PERMIT*FISHERY / NOPRINT OUT = FISHERY_BY_PERMIT;
     TITLE2 'FISHERY BY PERMIT';
RUN;
PROC PRINT;
RUN;

DATA FISHERY_BY_PERMIT_1; SET FISHERY_BY_PERMIT; BY PERMIT FISHERY;
     IF FIRST.PERMIT;
     F1 = 1;
     RENAME FISHERY = FISHERY1;

DATA FISHERY_BY_PERMIT_2; SET FISHERY_BY_PERMIT; BY PERMIT FISHERY;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_2; SET FISHERY_BY_PERMIT_2; BY PERMIT FISHERY;
     IF FIRST.PERMIT;
     F2 = 1;
     RENAME FISHERY = FISHERY2;

DATA FISHERY_BY_PERMIT_3; SET FISHERY_BY_PERMIT; BY PERMIT FISHERY;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_3; SET FISHERY_BY_PERMIT_3; BY PERMIT FISHERY;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_3; SET FISHERY_BY_PERMIT_3; BY PERMIT;
     IF FIRST.PERMIT;
     F3 = 1;
     RENAME FISHERY = FISHERY3;

DATA FISHERY_BY_PERMIT_4; SET FISHERY_BY_PERMIT; BY PERMIT;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_4; SET FISHERY_BY_PERMIT_4; BY PERMIT;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_4; SET FISHERY_BY_PERMIT_4; BY PERMIT;
     IF FIRST.PERMIT THEN DELETE;
DATA FISHERY_BY_PERMIT_4; SET FISHERY_BY_PERMIT_4; BY PERMIT;
     IF FIRST.PERMIT;
     F4 = 1;
     RENAME FISHERY = FISHERY4;


DATA FISHERIES; MERGE FISHERY_BY_PERMIT_1 FISHERY_BY_PERMIT_2 FISHERY_BY_PERMIT_3 FISHERY_BY_PERMIT_4;
     BY PERMIT;
     FISHERIES = SUM(OF F1  F2  F3  F4);
     DROP COUNT PERCENT F1 F2 F3 F4 FISHERY4;
RUN;

PROC FREQ;
     TABLES FISHERIES / OUT = FISHERIES_FREQ;
     TITLE2 'FREQ OF FISHERIES BY PERMIT';
RUN;

     

PROC SORT DATA = ALLPERMITS3; BY PERMIT FISHERY;
PROC MEANS SUM NOPRINT DATA = ALLPERMITS3; BY PERMIT FISHERY;
     VAR &SPECIES_LIST;
      OUTPUT OUT = HARVEST_BY_PERMIT_FISHERY SUM = RED KING COHO PINK CHUM;

DATA HARVEST_BY_PERMIT_FISHERY; SET HARVEST_BY_PERMIT_FISHERY;
     IF FISHERY = '' THEN DELETE;
     RENAME _FREQ_ = DAYS;
      DROP _TYPE_;
PROC PRINT DATA = HARVEST_BY_PERMIT_FISHERY (OBS = 50);
     TITLE2 'HARVEST BY PERMIT FISHERY';
RUN;

PROC SORT DATA = ALLPERMITS3; BY PERMIT ALLOWED;
PROC MEANS SUM NOPRINT DATA = ALLPERMITS3; BY PERMIT ALLOWED;
     VAR &SPECIES_LIST;
     OUTPUT OUT = HARVEST_BY_PERMIT SUM = RED KING COHO PINK CHUM;

DATA HARVEST_BY_PERMIT; SET HARVEST_BY_PERMIT;
     RENAME _FREQ_ = TRIPS;
     SALMON = SUM(OF RED KING COHO PINK CHUM);
     IF SALMON = . THEN SALMON = 0; 
     PERCENT_ALLOWED = ROUND((SALMON/ALLOWED)*100,1);
     DROP _TYPE_;
PROC PRINT DATA = HARVEST_BY_PERMIT (OBS = 50);
     TITLE2 'HARVEST BY PERMIT';
RUN;

PROC FREQ DATA = HARVEST_BY_PERMIT;
     TABLES PERCENT_ALLOWED;
     TITLE2 'PERCENT OF ALLOWED';
RUN;

DATA CHECK; SET HARVEST_BY_PERMIT;
     IF PERCENT_ALLOWED = .;
     TITLE2 'THESE PERMITS DO NOT HAVE A LIMIT';
PROC PRINT;
RUN;

DATA CHECK2; SET HARVEST_BY_PERMIT;
     IF PERCENT_ALLOWED GT 100;
     TITLE2 'THESE PERMITS ARE OVER THE LIMIT';
PROC PRINT;
RUN;

PROC SORT DATA = ALLPERMITS3; BY HARVDATE FISHERY;
PROC MEANS DATA = ALLPERMITS3 SUM NOPRINT; BY HARVDATE FISHERY;
     ID MONTH DAY;
     VAR RED PINK COHO CHUM KING;
     OUTPUT OUT = DAILY SUM = RED PINK COHO CHUM KING N = TRIPS;

DATA DAILY; SET DAILY (DROP= _TYPE_ _FREQ_);
     YEAR = YEAR(HARVDATE);
     IF YEAR = 1990 THEN DELETE;
     IF YEAR = . THEN DELETE;
     DROP MONTH DAY YEAR;

PROC SORT; BY FISHERY HARVDATE;
PROC PRINT DATA = DAILY (OBS = 25);
     TITLE2 'DAILY HARVEST ESTIMATES';

RUN;




/*
PROC EXPORT DATA= WORK.FISHERY_BY_CITY
            OUTFILE= "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS 2004 EXTRA ESTIMATES.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="FISHERY BY CITY"; 
RUN;

PROC EXPORT DATA= WORK.HARVEST_BY_PERMIT_FISHERY
            OUTFILE= "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS 2004 EXTRA ESTIMATES.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="HARVEST BY PERMIT AND FISHERY"; 
RUN;

PROC EXPORT DATA= WORK.HARVEST_BY_PERMIT
            OUTFILE= "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS 2004 EXTRA ESTIMATES.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="HARVEST BY PERMIT"; 
RUN;


PROC EXPORT DATA= WORK.DAILY
            OUTFILE= "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS 2004 EXTRA ESTIMATES.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="DAILY HARVEST BY FISHERY"; 
RUN;

PROC EXPORT DATA= WORK.FISHERIES
            OUTFILE= "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS 2004 EXTRA ESTIMATES.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="FISHERIES BY PERMIT"; 
RUN;


PROC EXPORT DATA= WORK.FISHERIES_FREQ
            OUTFILE= "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR\PU PERMITS 2004 EXTRA ESTIMATES.XLS" 
            DBMS=EXCEL2000 REPLACE;
            SHEET="NUMBER OF FISHERIES SUMMARY"; 
RUN;
*/







