****************************************************************************************;
*     There are 3 programs to analyze the salmon and shellfish permit databases:       *;
*         1. permits.sas                                                               *;
*         2. harvest.sas                                                               *;
*         3. estimates.sas                                                             *;
*     This program reads and modifies data for harvest                                 *;
*     This program is stored as h:\common\pat\permits\salmon\2002\harvest.sas          *;
****************************************************************************************;


*** SEARCH FOR QQQ;

%LET PROJECT = SALMON;
%LET DATA = CISLHV04C;
%LET YEAR = 2004;
%LET SP = SALMON;
%LET SPECIES_COMMA = RED,KING,COHO,PINK,CHUM; *QQQ;
%LET SPECIES_LIST = RED KING COHO PINK CHUM; *QQQ;
%LET PROGRAM = HARVEST;
%LET GILLNET_START = '15JUN04'D; 
%LET GILLNET_STOP = '24JUN04'D; 


OPTIONS PAGENO=1;
OPTIONS NODATE;
OPTIONS SYMBOLGEN;
LIBNAME SASDATA BASE "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR";
*ODS RTF FILE = "H:\COMMON\PAT\PERMITS\&PROJECT\&YEAR\&PROGRAM..RTF";
RUN;


TITLE1 "&PROJECT - &YEAR";


**************************************************************************;
*                              HARVEST DATA                              *;
**************************************************************************;

PROC CONTENTS DATA = SASDATA.&DATA;
RUN;

PROC FREQ DATA = SASDATA.&DATA;
     TABLES nohrvrpt;
RUN;


/*
DATA COMMENTS; SET SASDATA.&DATA;
     WHERE COMMENTS NE '';
   * KEEP PERMITNO COMMENTS;
run;

PROC EXPORT DATA= WORK.COMMENTS 
            OUTFILE= "H:\common\PAT\Permits\Salmon\&YEAR\&PROGRAM COMMENTS.xls" 
            DBMS=EXCEL2000 REPLACE;
RUN;
*/

DATA HARVEST; SET SASDATA.&DATA (DROP =  YEAR KEYDATE HVRECID MAILING KEYID EDITED);
     SPECIES = 'SALMON';  *QQQ;
   * IF HARVDATE EQ '01JAN01'D THEN HARVDATE = .;
     IF NOCATCH = 1 THEN CATCH = 'N'; IF NOCATCH NE 1 THEN CATCH = 'Y';
     IF NOHRVRPT = 1 THEN HRVRPT = 'N'; IF NOHRVRPT NE 1 THEN HRVRPT = 'Y';
     IF FISHERY = '' THEN FISHERY = 'UNKNOWN';
     RENAME PERMITNO = PERMIT;
     DROP NOCATCH NOHRVRPT COMMENTS;
RUN;

DATA HARVEST; SET HARVEST;
     MONTH = MONTH(HARVDATE);
     DAY = DAY(HARVDATE);
     IF FISHERY = 'KENAI' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KENAI' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH LE 5 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 6 AND DAY LT 15 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH GE 9 THEN HARVDATE = '01JAN90'D;
     IF FISHERY = 'KASILOF' AND MONTH EQ 8 AND DAY GT 7 THEN HARVDATE = '01JAN90'D;
     DROP MONTH DAY;
RUN;



PROC SORT DATA = HARVEST; BY PERMIT;     
PROC PRINT DATA = HARVEST (OBS = 40);
     TITLE2 'HARVEST FILE';
     TITLE3 ;
RUN;

PROC FREQ;
     TABLES CATCH HRVRPT HARVDATE FISHERY;
RUN;

PROC FREQ;
     TABLES &SPECIES_LIST;
     TITLE2 'HARVEST DATABASE';
     TITLE3 ;
run;


PROC UNIVARIATE PLOT;
     VAR &SPECIES_LIST;
RUN;


     
DATA SASDATA.SALMON_HARVEST; SET HARVEST; *QQQ;
RUN;


PROC SORT DATA = SASDATA.SALMON_HARVEST; BY HARVDATE FISHERY;
PROC MEANS DATA = SASDATA.SALMON_HARVEST SUM NOPRINT; BY HARVDATE FISHERY;
     VAR RED PINK COHO CHUM KING;
     OUTPUT OUT = DAILY SUM = RED PINK COHO CHUM KING N = TRIPS;

DATA DAILY; SET DAILY (DROP= _TYPE_ _FREQ_);
     LOCATION = FISHERY;
     DROP FISHERY;

DATA DAILY; SET DAILY;
     LENGTH FISHERY $18.;
     IF LOCATION EQ 'KASILOF' AND HARVDATE GE &GILLNET_START AND HARVDATE LE &GILLNET_STOP THEN FISHERY = 'KASILOF GILLNET';  *GILLNET;
     IF LOCATION EQ 'KASILOF' AND FISHERY = '' THEN FISHERY = 'KASILOF DIPNET';  *DIPNET;
     IF FISHERY = '' THEN FISHERY = LOCATION;
     DROP LOCATION;
PROC SORT; BY FISHERY HARVDATE;

PROC EXPORT DATA= WORK.DAILY 
            OUTFILE= "H:\common\PAT\Permits\Salmon\&YEAR\DAILY REPORTED.xls" 
            DBMS=EXCEL2000 REPLACE;
RUN;

*ODS RTF CLOSE;
RUN;

