PROC IMPORT OUT= WORK.HARVEST_BY_PERMIT 
            DATAFILE= "H:\common\PAT\Permits\Salmon\2004\PU PERMITS 2004
 EXTRA ESTIMATES.XLS" 
            DBMS=EXCEL REPLACE;
     SHEET="HARVEST_BY_PERMIT$"; 
     GETNAMES=YES;
     MIXED=NO;
     SCANTEXT=YES;
     USEDATE=YES;
     SCANTIME=YES;
RUN;
